### ISSUE TITLE
macOS 10.12 not supported?

### ISSUE THREAD

**Issue by brangusD** [happypandax/happypandax#100]
**Logs**
```
$ ./happypandax --gen-config
[50894] Error loading Python lib '/Users/foo/HappyPanda X.app/Contents/MacOS/Python': dlopen: dlopen(/Users/foo/HappyPanda X.app/Contents/MacOS/Python, 10): Symbol not found: _futimens
  Referenced from: /Users/foo/HappyPanda X.app/Contents/MacOS/Python (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/foo/HappyPanda X.app/Contents/MacOS/Python
```

**Environment:**
 - macOS 10.12.6
 - HPX Version v0.8.1

tbh, it was kind of a pain getting all of the deps right before, so i was excited to see macOS releases along with the claim of portability.

is it technically feasible to fix this in future releases, or am i stuck with using it from source if my version of macOS doesn't match what you built for?

**Comment by brangusD** [comment]
another option:

https://github.com/happypandax/happypandax/issues/101

**Comment by twiddli** [comment]
Hi, thanks for the report.
I haven't tested on OS X in a long time and have to rely on users to report these issues.
I'll look into fixing it for the next update.

**Comment by twiddli** [comment]
The CI website that I use to build binaries with seems to use macOS 10.13. This means that macOS 10.12 isn't supported no. That's unfortunate.

If more people ask for the docker solution, I'll start providing that. For now I guess you'll have to make one yourself. Base a container on an ubuntu image or something and then download the binaries for Linux. I think with this you should be able to use HPX without issue. It'll even auto-update itself, so no need to think about that.
