### ISSUE TITLE
docker release?

### ISSUE THREAD

**Issue by brangusD** [happypandax/happypandax#101]
have you ever considered doing a [docker](https://docs.docker.com/compose/) application as one more release option? i'd use it if you did. :)

**Comment by twiddli** [comment]
It's been considered before.
I was waiting for people to inquire.
I'll add it If more people probe about it.

**Comment by brangusD** [comment]
one thing to consider if you do is having some mechanism for backup/restore without forcing the user to tear into your docker container volumes and try to manually get the data out.

if hpx already supports making a backup of the db (and maybe settings if it make sense to do so?) via the web client then perfect.

and then how to get manga into hpx?
will you have the user specify a `volumes:` path in `docker-compose.yml` to so that hpx can access a host-side manga directory at runtime?

**Comment by twiddli** [comment]
I haven't implemented any backup mechanism yet, but being able to download the backup through a client seems like a good idea.

>  will you have the user specify a path in docker-compose.yml using volumes so that hpx can access a host-side manga directory at runtime?

I think that is the only way? Or the webclient has to support uploading manga.

**Comment by GirthHub69** [comment]
I would also love an option for docker.
I haven't been able to use HPX ever since you closed sourced it since your OSX builds are only usable on one version of OSX. :(

**Comment by naipilk** [comment]
Also requesting a docker image. Would be great.
Thanks for the consideration.

**Comment by twiddli** [comment]
I see that several people want this.
I'll try putting one out for the next version.

**Comment by waz1500** [comment]
I would actually love a docker image. I should have posted my interest long ago. 
Alpine linux is very lightweight in terms of size and could be a great starting base for the HPX image.

**Comment by twiddli** [comment]
this has now been added for `v0.11.0`
