### ISSUE TITLE
Image does not fit to screen properly

### ISSUE THREAD

**Issue by Morrida** [happypandax/happypandax#104]
Hey there. Since the UI redesign earlier this year/late last year, I've noticed some odd behaviour with portrait mode on the device I use to view HPX. The device in question is a Surface Pro 3 with a native resolution of 2160 x 1440. Browser is Firefox on W8.1.

In landscape mode when viewing a gallery, fit to height works as expected - The image is scaled to the height of the viewport, black bars are present either side. In portrait mode, the image is pushed over because of the navigation on the left side, cutting off the right 1/10th (estimated) of the image. If the image is lower resolution, it is all visible, albeit off centre. Fit to width also does not have the intended behaviour.

I've uploaded screenshots to imgur because I suppose github doesn't like my screenshots. https://imgur.com/a/tKKZLQk

I've also noticed clicking on a gallery image doesn't snap the image to the top of the viewport, dunno if that's related or should be a separate issue.

Cheers.

**Comment by twiddli** [comment]
Hi, it would have been better if you followed the template for reporting bugs so I don't need to ask these things.
I can see from the screenshot that you're not using the latest version of HPX. Which version are you using?
And what Firefox version?

**Comment by Morrida** [comment]
Hi, sorry about that.

Firefox 66.0 x64
HPX Server 0.9.1 DB 0.6.0

I'll try clearing cached content for the client, just in case.

**Comment by Morrida** [comment]
Here's the templated response so you have everything

**Describe the bug**
Since the UI redesign earlier this year/late last year, I've noticed some odd behaviour with portrait mode on the device I use to view HPX. The device in question is a Surface Pro 3 with a native resolution of 2160 x 1440. Browser is Firefox on W8.1.

In landscape mode when viewing a gallery, fit to height works as expected - The image is scaled to the height of the viewport, black bars are present either side. In portrait mode, the image is pushed over because of the navigation on the left side, cutting off the right 1/10th (estimated) of the image. If the image is lower resolution, it is all visible, albeit off centre. Fit to width also does not have the intended behaviour.

**To Reproduce**
Steps to reproduce the behavior:
1. Have display resolution around 1440 x 2160 (3:2, portrait mode)
2. Go to any gallery with images equal or greater than portrait horizontal resolution
3. Set scaling to fit height, doesn't really matter
4. Image is cut off

**Expected behavior**
The right edge of the image does not go off screen, per screenshots

**Logs**
If applicable, include your ``error.log`` or ``debug.log`` found in ``[HPX]\logs\`` to help identifying your problem.
N/A

**Screenshots**
If applicable, add screenshots to help explain your problem.
https://imgur.com/a/tKKZLQk

**Environment:**
 - OS: Windows 8.1 (client) Server: Server 2012 R2
 - Browser and browser version [e.g. chrome 61, firefox 60] Firefox 66.0 x64
 - HPX Version [e.g. 22] Server 0.9.1 DB 0.6.0

**Additional context**
Add any other context about the problem here.
assf

**Comment by Morrida** [comment]
Hi, no change after clearing cache and trying in incognito. I'll try a fresh download and move the DB across in case web components did not update properly. The actual folder is from 0.6.1.

**Comment by twiddli** [comment]
Are you able to replicate it in FF responsive mode? because I'm not

**Comment by twiddli** [comment]
Also, can you try scrolling all the way down and see if you can see this button?
![billede](https://user-images.githubusercontent.com/11841002/55267767-40514100-527c-11e9-9e0a-e59c854e3073.png)

**Comment by Morrida** [comment]
Hi, yes I can replicate it at 1200x1800 in responsive mode. Gallery view setting:

Scaling: fit height
Size: original
stretch is unchecked.

That button is present down the bottom, pushed hard up against the info box. I'm going to check if Windows display scaling is acting up.

**Comment by twiddli** [comment]
Okay, it has been fixed

**Comment by Morrida** [comment]
Thank you very much for your work! :+1: Guessing this will be included in the next build?

**Comment by twiddli** [comment]
should be fixed in `v0.9.2`
