### ISSUE TITLE
Error when trying to add galleries using Postgres

### ISSUE THREAD

**Issue by ub333** [happypandax/happypandax#105]
**Describe the bug**
When attempting to scan for new galleries, HPX immediately gives the following error in the output window: 

`[CommandError|120]: Command(107) has failed with: [HappypandaError|100]: ProgrammingError((psycopg2.ProgrammingError) column "page.path" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: ...RE "c_115cc0ef0_1" CURSOR WITHOUT HOLD FOR SELECT page.path ... ^ [SQL: SELECT page.path AS page_path FROM page GROUP BY page.gallery_id] (Background on this error at: http://sqlalche.me/e/f405))`

**To Reproduce**
1. Set db dialect to postgres
2. Launch HPX
3. Go to "scan"; enter a valid path; click "Scan"

**Expected behavior**
Should properly scan for new galleries - works for me when using sqlite but not postgres.

**Logs**
[error.log](https://github.com/happypandax/happypandax/files/3025946/error.log)

**Screenshots**
<img width="1122" alt="Screen Shot 2019-03-30 at 1 47 24 PM" src="https://user-images.githubusercontent.com/46982788/55281597-0459c280-52f4-11e9-9d53-95075a133ac8.png">

**Environment:**
 - OS: macOS 10.14.4
 - Chrome 73
 - HPX Version 0.9.1

**Additional context**
Note that this is a newly created and empty database.

**Comment by twiddli** [comment]
Hi, thanks for reporting. A fix is coming out shortly.

**Comment by ub333** [comment]
Sweet, thanks for the quick feedback!

**Comment by twiddli** [comment]
should be fixed in `v0.9.2`
