### ISSUE TITLE
Clicking "Read" on the "What to read next..." page doesn't open the book in question.

### ISSUE THREAD

**Issue by wotus043** [happypandax/happypandax#106]
**Describe the bug**
Clicking "Read" on the "What to read next..." page doesn't open the book in question, rather it just goes to the start of the currently open book. Opening it in a new tab works fine though.

**To Reproduce**
1. Open any book and go to the end.
2. Click on any of the suggested books.
3. It just opens the book you just read.

**Expected behavior**
The book you selected opens.

**Screenshots**
https://0x0.st/zPuI.mp4 (nsfw)

**Environment:**
 - OS: Windows 10 x64
 - Browser and browser version: Firefox Nightly 68.0a1
 - HPX Version: 0.9.2

**Comment by twiddli** [comment]
fixed in HPX `v0.10.0`
