### ISSUE TITLE
Provide option to select all galleries from current list in select mode

### ISSUE THREAD

**Issue by emmauss** [happypandax/happypandax#107]
**Is your feature request related to a problem? Please describe.**
Currently in select mode for the library, you can only select each gallery one at a time. So, if you want to select a large number of galleries( or at least, the amount on the current page), you would have to click each and everyone of the galleries, which takes a lot of time.

**Describe the solution you'd like**
An option to select all items on the current screen/page would help.

**Describe alternatives you've considered**
Being able to drag select would be a great plus. A Control/Shift selection could improve it further.

**Comment by twiddli** [comment]
this should now be available in `v0.11.0`
