### ISSUE TITLE
[DatabaseError|300]: DetachedInstanceError(Parent instance <Title at 0x91aecd0> is not bound to a Session; lazy load operation of attribute 'language' cannot proceed

### ISSUE THREAD

**Issue by Indy27** [happypandax/happypandax#108]
**Describe the bug**
It always happen when I try to add metadata to a lot of galleries and only seems to be a sqlite error (I tried to use figuring out how to postgresql working on HPX but gave up). Whatever this is is preventing me to implement a gallery's tags and the rest of the information. I don't know if it's a database issue, or plug-in issue, or unexplained.

**To Reproduce**
1. Library or Inbox
2. Query Metadata
3. Error pops-up (I know for a fact all the COMIC1 with a star next to it, or maybe just certain symbols themselves)  EDITED: Disregard the COMIC1 thing, I just tried a COMIC1*13 doujin and it worked.

**What It Should Be Doing**
Properly input metadata into the galleries

**Logs**
[activity.log](https://github.com/happypandax/happypandax/files/3075603/activity.log)
 Just ctrl+F sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <Title at 0x867ef270> is not bound to a Session; lazy load operation of attribute 'language' cannot proceed

**Screenshots**
![Untitled-2](https://user-images.githubusercontent.com/16329147/56072757-131a8d80-5d68-11e9-9acf-60690ef66be7.jpg)

**Environment:**
 - OS: Windows 10
 - Browser and browser version [Chromium (dunno what version)], Waterfox 52.0
 - HPX Version [latest one]

**Comment by twiddli** [comment]
fixed in HPX `v0.10.0`
