### ISSUE TITLE
Failed to create a new user

### ISSUE THREAD

**Issue by otica** [happypandax/happypandax#110]
**Describe the bug**
I tried to create a new user other than log in as default but there is no repsonse from the command line exe and it stops at this stage so I cannot enter --create-user
![捕获](https://user-images.githubusercontent.com/39248909/57521082-eb601a80-7351-11e9-9d67-c6036f9ac65e.PNG)
Did I do some steps wrong?

Update:
Now I cannot log in as default even. I have not changed anything. This error shows when it starts.
![屏幕截图(533)](https://user-images.githubusercontent.com/39248909/57526200-4d734c80-735f-11e9-8e31-7e8b0090a87b.png)

**To Reproduce**
1. Go to happypandax.exe
2. Click it
3. See error

**Logs**
[error.log](https://github.com/happypandax/happypandax/files/3166069/error.log)
[activity.log](https://github.com/happypandax/happypandax/files/3166070/activity.log)

**Environment:**
 - OS: win10 chinese version
 - chrome 61
 - HPX Version 0.9.2 the latest version

**Additional context**
Will you add more language supports in the future?

**Comment by twiddli** [comment]
Hi, I've just fixed a bug for the upcoming version about the default superuser not being created correctly, hence the error you see.

I'm able to create a user successfully though:
![billede](https://user-images.githubusercontent.com/11841002/57588371-92d87b00-7513-11e9-98be-bd5ca0c0b831.png)

**Comment by twiddli** [comment]
fixed in HPX `v0.10.0`
