### ISSUE TITLE
Possible duplicates from rescans.

### ISSUE THREAD

**Issue by emmauss** [happypandax/happypandax#111]
**Describe the bug**
Duplicates of already added galleries can occur if scans of the same directory are done. This is probably caused by the scanner not doing some postproccessing that the converter would have done. When scanning on an already scanned directory, esp. after you add galleries to the directory and want to add them to the db, old entries from the directory are also included in the results, and when submitted, creates duplicates. This does not occur for galleries added using the converter.

**To Reproduce**
1. Scan and add galleries from a directory,
2. Redo the scan.
3. Check results, and submit.

**Expected behavior**
No galleries should be found with the second scan.

**Environment:**
 - OS: Windows
 - Firefox 66
 - HPX Version 0.9.2

**Comment by twiddli** [comment]
fixed in v0.10.1
