### ISSUE TITLE
Visible indication of a completed gallery scan result submission

### ISSUE THREAD

**Issue by emmauss** [happypandax/happypandax#112]
**Is your feature request related to a problem? Please describe.**
As something that could help with #111 , having a visible notice of a completed scan result submission completion would help user know when a scan is complete. Currently, only the progressbar is the indicator, and only when it stops animating would you know it's done.

**Describe the solution you'd like**
A notice, like a dialog or text saying submission complete. A warning that a submission is still going on if the user tries to navigate away or reload the page will help.

**Additional context**
Chances are that a submission could fail if the user does not know when a submission is done and closes the tab, or navigate elsewhere, as the bar fills up after the first part of the submission, and it takes long till it stops animating. It could be the reason for my duplicate gallery issue.

**Comment by twiddli** [comment]
added in v0.10.1
