### ISSUE TITLE
Crop Image Titles So They Aren't Too Long

### ISSUE THREAD

**Issue by Astromormy** [happypandax/happypandax#113]
Some of the comics that I add into the program have very long pages, so when the gallery/inbox displays them next to all, the very long pages disrupt the view of the rest of the comics. Could you add a functionality that would crop the images so all the titles align correctly?

**Comment by twiddli** [comment]
Hi, a screenshot of the issue would be helpful. Please fill out the template next time.

**Comment by twiddli** [comment]
this should now be fixed in `v0.11.0`
