### ISSUE TITLE
Can't add new galleries.

### ISSUE THREAD

**Issue by TheJoe49** [happypandax/happypandax#116]
**Describe the bug**
Whenever I try to scan for new galleries it freezes on the last few and wont add any of them, and when I do get it to add galleries it adds duplicate ones, even with "scan only for new galleries turned on". I have tried a fresh install and I have tried letting it sit over night.

**Expected behavior**
Add galleries and not add the same one twice.

**Logs**
[debug.log](https://github.com/happypandax/happypandax/files/3323364/debug.log)
[error.log](https://github.com/happypandax/happypandax/files/3323365/error.log)
[activity.log](https://github.com/happypandax/happypandax/files/3323366/activity.log)

**Screenshots**

![Screenshot_4](https://user-images.githubusercontent.com/16162727/60066093-bb839100-96cb-11e9-9490-dabcdf3b500c.png)

**Environment:**
 - OS: Windows
 - Chrome
 - HPX Version 0.10.0

**Comment by twiddli** [comment]
This should now be fixed in v0.10.1
