### ISSUE TITLE
Can't add Galleries on scanning 

### ISSUE THREAD

**Issue by emoleek** [happypandax/happypandax#117]
**Describe the bug:**

When i press the submit button on the scanning page , the result is always completed with error . And after that the gallery i previous scan will not be added .

**Step to reproduce :**

1. Scan a gallery 
2. Press submit button

**Expected behavior:**

The gallery be added

**Logs**

[activity.log](https://github.com/happypandax/happypandax/files/3343949/activity.log)
[error.log](https://github.com/happypandax/happypandax/files/3343950/error.log)
[plugin.log](https://github.com/happypandax/happypandax/files/3343951/plugin.log)
[redis_stdout.log](https://github.com/happypandax/happypandax/files/3343952/redis_stdout.log)

**Screenshot:**

![Capture3](https://user-images.githubusercontent.com/46783298/60411006-097d2500-9bf5-11e9-8695-9d83cb2280e4.JPG)

**Environment:**

OS: Windows 10
Browser: Chrome
Version : 0.10.1

**Comment by twiddli** [comment]
Hi, I believe this should now be fixed in v0.10.2
Please re-open the issue if it still persists.
