### ISSUE TITLE
Configurable thumbnail resolutions

### ISSUE THREAD

**Issue by Waiifu** [happypandax/happypandax#119]
So basically, I've been messing around with the CSS, and among making it dark-theme, I decided I'd rather have far larger covers. Now making the covers on the larger on the CSS is easy enough, but I'm not sure how to go about making the actual resolution of the generated thumbnails larger.

 Is there any way to do so?

**Comment by twiddli** [comment]
Hi, unfortunately, the cover sizes are hardcoded atm. but it should be easy enough to expose some settings to configure it.

> dark-theme

i'm curious about this, would you be okay with sharing a screenshot of this?

**Comment by Waiifu** [comment]
I threw the current dark-theme CSS together in like 15 minutes, it's extremely rough, but I'm planning on redoing it entirely and more properly, making it actually decent. Here's some screenshots of it as is right now anyway. 

The cover sizing is a bit janky right now as well, since I also didn't have enough time to go adjust the grid width fittings to accommodate the larger covers.

[Browse](https://i.imgur.com/HNZPyGs.jpg)
[Quick Info](https://i.imgur.com/dzGGvMk.png)
[Gallery 1](https://i.imgur.com/RRVXpZr.png)
[Gallery 2](https://i.imgur.com/9M2QZEx.png)

**Comment by twiddli** [comment]
this should now be possible in `v0.11.0`, check the new setting `advanced.image_sizes`

**Comment by Waiifu** [comment]
I can't seem to figure out the syntax of the setting. 

If I try to copy-paste the default https://i.imgur.com/vgDJBlK.png, after shutting HPX down it turns into https://i.imgur.com/KUDXKwB.png. And changing the values at that state doesn't seem to do anything, am I doing something incorrectly?

**Comment by twiddli** [comment]
Hello, the format in the last screenshot should be correct, but you may need to clear the thumbnail cache to see any immediate results.
You clear the thumbnail cache by deleting the contents of `static/thumbnails`

**Comment by Waiifu** [comment]
I did so, between every test/attempt, incl. complete restarts of HPX.

**Comment by twiddli** [comment]
Remove the single-quotes around the keys, I think they might be interfering.
`'big'` -> `big`

**Comment by Waiifu** [comment]
That was indeed it, thanks!
