### ISSUE TITLE
How do I make it work with my phone and laptop over my network.

### ISSUE THREAD

**Issue by niplover** [happypandax/happypandax#121]
I'm new to happypandax. I clicked on happypandaxGUI and managed to set up my server. I set it up on my Desktop. It opened a tab in my browser with a localhost address. Such as 10.0.0.12, etc... I the typed that into the address by of chrome on my phone and laptop, but it could not reach it the site. I can't figure out what I'm doing wrong.

**Comment by twiddli** [comment]
Hello, try following this tutorial, if you're on windows:
https://happypandax.github.io/usage.html#private-network

After that you need to figure out what your local IP address is. You can use this guide https://lifehacker.com/how-to-find-your-local-and-external-ip-address-5833108

On your phone or laptop connected to the same network, type your local IP address into the address bar like this `local_ip:port`, where `port` is the port you started the HPX webserver on (this is `7008` by default)

**Comment by niplover** [comment]
Thank you so much. I tried to follow it but the initial part has me confused. "When starting HPX, set the two settings server.host and server.host_web to 0.0.0.0. This means that the server should " this has me confused. By starting HPX does it mean the HappyPandax_GUI.exe? Because I couldn't find those settings there to change. At least not verbatim. I found a couple that looked similar.

**Comment by twiddli** [comment]
If you're using the gui click on the tabs **Configuration** -> **server**. Change the value for `host` and `host_web` in there.

**Comment by twiddli** [comment]
Considered resolved
