### ISSUE TITLE
Plugin pages do not load if guest authentication is disabled

### ISSUE THREAD

**Issue by CirnoT** [happypandax/happypandax#123]
**Describe the bug**
Accessing any plugin page (for example E-Hentai Login plugin) at ```/plugin/d9b1d111-7250-4083-9efb-356fabbeada7/login``` shows login screen, but filling credentials (or skipping with default) fails with error ```[AuthMissingCredentials|412]: [AuthMissingCredentials|412]: [InvalidMessage|403]: JSON dict missing 'user' key``` unless guest authentication is enabled in config.

**To Reproduce**
^ See above

**Expected behavior**
Plugin configuration page is shown after entering admin credentials

**Logs**
n/a

**Screenshots**
n/a

**Environment:**
 - OS: Linux
 - Browser and browser version: Chromium 75
 - HPX Version: 0.10.2 server, 0.10.1 client

---

**Additional context**
n/a

**Comment by twiddli** [comment]
this should now be fixed in `v0.11.0`
