### ISSUE TITLE
Open Plugin Site link in client links to full URL that server listens on

### ISSUE THREAD

**Issue by CirnoT** [happypandax/happypandax#124]
**Describe the bug**
'Open Plugin Site' link under Plugins links to full URL that server listens on, for example ```http://localhost:7008/plugin/d9b1d111-7250-4083-9efb-356fabbeada7``` which breaks when server is exposed with reverse proxy in place to server HTTP requests (such as nginx)

**To Reproduce**
1. Have HPX WWW server listen on localhost and expose it over nginx reverse proxy
2. Go to About
3. Move to Plugins tab
4. Enable E-Hentai Login plugin
5. Click 'Open Plugin Site' link

**Expected behavior**
Links is provided to relative URL allowing browser to fill current domain itself.

**Logs**
n/a

**Screenshots**
n/a

**Environment:**
 - OS: Linux
 - Browser and browser version: Chromium 75
 - HPX Version: 0.10.2 server, 0.10.1 client

**Additional context**
n/a

**Comment by twiddli** [comment]
this should now be fixed in `v0.11.0`
