### ISSUE TITLE
Component Tokens for Gallery Scanner not working

### ISSUE THREAD

**Issue by coalsock** [happypandax/happypandax#129]
I'm having trouble understanding how the component-tokens for the scanner works. 

Lets say I have the following file path:
D:/Directory/MixedReal/(C87) [Xration (mil)] MIXED-REAL Union (Zeroin) [English] [biribiri].zip

I want the scanner to treat MixedReal as a collection and all the files in it as galleries, so I assume I should input the following into the scanner:
D:/Directory/{collection}/{gallery}

However, the scanner comes up blank when I do so; it does not show any of the galleries I want to be imported into HPX. I'm not certain if I am using the component-tokens incorrectly, could you help with this issue? Thanks!

**Comment by twiddli** [comment]
Hello,
I've confirmed that this is indeed not working as intended.

**Comment by twiddli** [comment]
this should now be fixed in `v0.11.0`
