### ISSUE TITLE
SOCKS5 proxy?

### ISSUE THREAD

**Issue by brozilian** [happypandax/happypandax#133]
Hey there, new account but I'm the guy that made a fuss about gallery detection with zip files in happypanda. Hope you're doing well.

Anyway, I've noticed the settings include HTTP and HTTPS proxies, but is it possible to add SOCKS5 support? I don't know how you handle DNS queries either but I'm the sort to worry about these things.

Also not sure if plugins respect proxy settings by default or not?

**Comment by twiddli** [comment]
Hello,
I am doing well, thank you

I will look into adding socks5 support.
Plugins will respect proxy settings provided that they use the HPX api for performing requests (which all the default plugins do)

**Comment by twiddli** [comment]
this should now be available in `v0.11.0`, check the changelog
