### ISSUE TITLE
Can't edit external link from browser

### ISSUE THREAD

**Issue by rwchunk** [happypandax/happypandax#134]
When you click on the title of a gallery from the browser you can see this menu
But you can't edit the external link field
![image](https://user-images.githubusercontent.com/19255865/62727161-7480ff00-b9de-11e9-8068-1d4f597a81b1.png)

Unless it already has one; the edit button on the right is present in this example:
![image](https://user-images.githubusercontent.com/19255865/62727093-51eee600-b9de-11e9-8bfe-2b0f4522c028.png)

**Comment by twiddli** [comment]
Hello, it's possible to enter new links by going to the page of the gallery in question and then clicking "Edit" at the top.
If you have any suggestions as to how to improve this, please create a new issue.
Also, please follow the issue templates.
