### ISSUE TITLE
Unable to use filters in postgres

### ISSUE THREAD

**Issue by Waiifu** [happypandax/happypandax#139]
**Describe the bug**
Whenever I attempt to make/use/update a filter, an error occurs. This only happens when I'm running on postgres.

**To Reproduce**
1. Go to Management
2. Make a new filter
3. Filter creates but contains no matching galleries
4. See error in console

**Logs**
[error.log](https://gist.github.com/Waiifu/4582a36222dd6d0b3925911127b3263e)

**Environment:**
 - OS: Arch Linux 5.2.8
 - FF69
 - HPX 0.10.2
- PostgreSQL 11.5

**Comment by twiddli** [comment]
this should now be fixed in `v0.11.0`
