### ISSUE TITLE
Unable to set up external image viewer

### ISSUE THREAD

**Issue by flimi** [happypandax/happypandax#141]
This likely due to a lack of knowledge from me but I am unable to set up an image viewer for my galleries nor do I know what would be appropriate for doing so. I have tried to use irfanview but have been completely unable to get it to take and have found no resources on doing so. Any help would be appreciated.

**Comment by twiddli** [comment]
1. Find out where the irfanview exectuable is stored
2. Open the HPX webclient
3. Open Preferences -> General
4. Paste the path to the irfanview executable in the External Image Viewer input
5. Make sure to toggle the "Open in external viewer" option you can find around the client

**Comment by flimi** [comment]
The problem is that the "open in external viewer" option doesn't seem to exist. I assume I need to add an argument to the external viewer to make it default but I'm tech illiterate and don't know how.

**Comment by twiddli** [comment]
![billede](https://user-images.githubusercontent.com/11841002/63695208-79d0ad00-c818-11e9-8812-6b4cf47c0953.png)
![billede](https://user-images.githubusercontent.com/11841002/63695274-9bca2f80-c818-11e9-9db5-7e273aaf3d3f.png)

**Comment by flimi** [comment]
Thanks for the help and sorry for my stupidity.
