### ISSUE TITLE
Plugins failing to load in 0.11

### ISSUE THREAD

**Issue by nopenopenop** [happypandax/happypandax#142]
I just upgraded to 0.11 (via the Windows Installer) and receive the following on startup:

>: Starting HappyPanda X
>: Using sqlite database
>: Checking for database update
>: Waiting on redis for maximum 20 seconds...
>: Starting webserver... (0.0.0.0:7008)
>: Loading plugins from path: plugins
>: Loading 4 plugins
>: Traceback (most recent call last):
>: File "src\gevent\greenlet.py", line 766, in gevent._greenlet.Greenlet.run
>: File "happypanda\core\plugins.py", line 1005, in _init_plugins
>: File "happypanda\core\plugins.py", line 1088, in _collect_dependencies
>: TypeError: argument of type 'MatchFirst' is not iterable
>: 2019-08-29T02:06:24Z
>: <Greenlet at 0x6c13250: <bound method PluginManager._init_plugins of <happypanda.core.plugins.PluginManager object at 0x03E6E090>>> failed with TypeError

I've tried cleaning out the plugin folder and grabbing the latest release and still receive the above. The plugins show as Not Enabled in the web client and there is no further way to interact with them via that interface. I was able to get to the Ehentai Login GUI page via directly accessing the URL but the form does not appear to be grabbing data. (During check_login, data.data is null.)

**Comment by ajtpak** [comment]
getting this same issue as well

**Comment by twiddli** [comment]
Yea, confirmed

**Comment by twiddli** [comment]
fixed in `v0.11.1`
