### ISSUE TITLE
Add Plugins to docker image

### ISSUE THREAD

**Issue by waz1500** [happypandax/happypandax#143]
**Is your feature request related to a problem? Please describe.**
I know it is possible to copy paste the plugins into /data folder manually. I've noticed the plugins are being bundled in with the newer releases (happypandax0.11.0.win.zip), however they are missing from the docker image.

**Describe the solution you'd like**
Would it be possible in the next docker image to bundle these plugins into it's respective folder?

**Comment by waz1500** [comment]
In the `0.11.0` release this was supposedly fixed.  `docker: plugins were not being bundled`

Although do they seem to be bundled now when I terminal into the container. The plugin folder from /data is still showing up as empty and not detected by HPX. 

```
backups/
cache/  
data/ 
logs/  
plugins/  
translations/
```

**Comment by twiddli** [comment]
yea, there was a mistake in the docker image

**Comment by twiddli** [comment]
should be ok now in `v0.11.2`
