### ISSUE TITLE
Failed to open gallery with external viewer

### ISSUE THREAD

**Issue by Sebleux** [happypandax/happypandax#145]
**Describe the bug**
External viewer not working.
Tried CDislayEx and CDisplay.
Tried launching them as admin and changing their location (tried putting them in the same folder as HappyPandaX)

Error :
WARNING [server].happypanda.core.server: Error on func 'open_gallery': CommandError('Failed to open gallery with external viewer: Access is denied',)

**To Reproduce**
1. Open gallery using external viewer
2. See error

**Logs**
[debug.log](https://github.com/happypandax/happypandax/files/3556713/debug.log)
[error.log](https://github.com/happypandax/happypandax/files/3556714/error.log)

**Environment:**
 - OS: Win10
 - HPX Version 0.11

**Comment by twiddli** [comment]
`C:\Program Files\CDisplayEx`
I see only the path to the folder being put in, not the actual executable. Try adding the path to the actual `.exe` file.

**Comment by Sebleux** [comment]
It worked. Thank you !
