### ISSUE TITLE
Better tagging

### ISSUE THREAD

**Issue by justforhentai** [happypandax/happypandax#146]
I would love to see auto tagging via .json files without link ex links with files:
[1.](https://nhentai.net/g/255636/)
 [2.](https://hitomi.la/galleries/836200.html)
[3.](https://e-hentai.org/g/1392034/ae85b8cb63/)
[json folder.zip](https://github.com/happypandax/happypandax/files/3562184/json.folder.zip)

**Comment by twiddli** [comment]
This is already possible with the [File Metadata](https://github.com/happypandax/plugins/tree/master/plugins/File%20Metadata) plugin
