### ISSUE TITLE
Creating default superuser 'default' on 0.11.x

### ISSUE THREAD

**Issue by Waiifu** [happypandax/happypandax#147]
**Describe the bug**
It seems even with guest, default user, disabled and require_auth enabled, a default superuser keeps getting generated at boot. This user doesn't show up in neither the database table nor the user's tab in the GUI. This user then can be logged into with either 'default' as username and no password, or just no input on both fields.

I've circumvented this for now by creating a manual user named "default", which then blocks logging in with no credentials by throwing a multiple users database error.

I've only used postgres in 0.11.x, so I don't know if this is an issue in SQLite as well.

**Expected behavior**
Default user being disabled stopping the creation / usage of default user.

**Logs**
Nothing of relevance contained in them particular to this issue.

**Screenshots**
https://i.imgur.com/TuDIYEK.png

**Environment:**
 - OS: Arch Linux Kernel 5.2.9
 - 69.0b16 (64-bit)
 - HPX Version 0.11.1 & 0.11.0

**Comment by twiddli** [comment]
Hi, `server.disable_default_user` just means it shouldn't be possible to login using the default user. Everything else is intentional.

I just tested it and can confirm that logging in with `disable_default_user` set to true is possible. This is a bug.

**Comment by twiddli** [comment]
fixed in `v0.11.2`
