### ISSUE TITLE
Show detailed progress when the scanner is looking through every folder

### ISSUE THREAD

**Issue by waz1500** [happypandax/happypandax#149]
**Is your feature request related to a problem? Please describe.**
Can't use regex tokens such as `{collection}/{series}/{gallery}` on nested folders. 

My manga is stored in structure like this:
`O:\Sorted\H-Manga\..`
and so when I try to scan and add using HPX `O:\Sorted\H-Manga\{collection}/{series}/{gallery}` it will fail to do so. 

whereas the regex tokens only work if I move everything and store it like this:
`O:\H-Manga\..`
HPX will detect the manga when it's sorted this way and so works. 
`O:\H-Manga\{collection}/{series}/{gallery}` 

**Describe the solution you'd like**
Is there are way to make HPX treat `O:\Sorted\H-Manga\` as the full root so I can use the tokens in nested a folder?
I have it setup like this because other applications such as torrents/database managers/etc use several folders within root and rely on this structure and it works for my workflow. 

I am aware that putting the entire collection onto the root folder fixes the problem but it be nice not to be forced to do so and to maintain personal organisation.

**Comment by twiddli** [comment]
I can't see why `O:\Sorted\H-Manga\{collection}/{series}/{gallery}` wouldn't work.
Can you provide any logs? Preferably debug logs.

**Comment by waz1500** [comment]
My apologies. This is actually working as intended. I believe because of the collection size, the progress indicator remains at `0%` until it's looked through every folder and then will list the results depending on the regex expression used. The whole process took a bit of time. 

Feature request:
Would it be possible to have a slightly more detailed percentage indicator showcasing work is being done or at least under the hood? If not, feel free to close the issue as my issue is solved.

**Comment by twiddli** [comment]
added in `v0.11.2`
