### ISSUE TITLE
Tag to gallery associations not removed on gallery deletion

### ISSUE THREAD

**Issue by failerko** [happypandax/happypandax#152]
**Describe the bug**
When I create a new gallery and set some tags that association is stored in DB table `taggable_tags`. Then when I delete that gallery, those associations don't get removed. So when I try to create new gallery with at least one tag the deleted gallery had, HPX throws an error. Alternatively when I create a new gallery and assign tags that old gallery didn't have, the gallery will be created with tags of the removed gallery as well as the new tags.

**To Reproduce**
1. Add new gallery with tags t1, t2
2. Completely remove gallery (move to trash and clean trash)
3. Try to create new gallery with tags t1, t2.

**Expected behavior**
New gallery should be created without any unwanted tags.

**Logs**
[debug.log](https://pastebin.com/F1hay9rZ)

**Environment:**
 - OS: Windows 10 1903
 - Browser and browser version Firefox 68.0.2
 - HPX Versions: 
    * Server version: 0.11.1
    * Webclient version: 0.11.0
    * Database version: 0.7.0

**Comment by twiddli** [comment]
There's a unittest for this so that it wouldn't happen, but I'll look into it.

**Comment by twiddli** [comment]
It seems that foreign keys constraints hadn't been working since 0.2.0 despite the tests. It's fixed now in `v0.12.0`
