### ISSUE TITLE
Flicking between size whilst having fixed scale causes image to become slightly washed.

### ISSUE THREAD

**Issue by waz1500** [happypandax/happypandax#154]
**Describe the bug**
Flicking between image size whilst having a fixed scale causes certain images to become slightly washed.

**To Reproduce**
1. Click on Manga to read
2. Change Scaling to "Fixed Height" (done so you can see the difference more clearly)
3. Click on x768 which causes the image to appear how it's intended within the JPEG file. This is the TRUE image.
3b. Clicking on something higher such as x2400 adds some sort of washed filter on top of it. 
4. See difference

**Screenshots**
![scale](https://user-images.githubusercontent.com/17833884/64429021-fda65700-d0ac-11e9-84a7-ea6fd7d80b89.jpg)
The image on the left is x768 view and the image on the right is x2400. 

**Expected behavior**
Changing the scale shouldn't affect the image in terms of color. 

I have no idea what is causing this and it's incredibly hard to see on other manga. It's hard to find another manga for more testing. I have included a zip of the image in question for testing purposes. 
[cover.zip](https://github.com/happypandax/happypandax/files/3583984/cover.zip)

Because this issue is so unique and doesn't affect HPX I totally understand if you don't want to fix this. 

****
**Environment:**
 - OS: Windows
 - Chrome Version 76.0.3809.132 (Official Build) (64-bit)
 - HPX Version 0.11.2

**Comment by twiddli** [comment]
If you refresh the page after changing size, does it still appear washed out?
Could you try other browsers?

**Comment by waz1500** [comment]
Refreshing the page still appears washed out. 
Only x768 and x960 modes appear to show the true image colors. Anything higher does not and appears washed. 

Issue still persists when using Microsoft Edge Browser. 
Microsoft Edge 44.18362.267.0
Microsoft EdgeHTML 18.18362

I tried with the latest version of HPX Desktop and it also appears to be adding a washed image look when scaling to a higher resolution also.

**Comment by twiddli** [comment]
This is a super old issue but I think might have figured out why this happens.
Using a chromium based browser, I get washed out images when hardware acceleration is enabled. This affects all sites. Disabling it fixes the issue.
This issue does not affect Firefox.
