### ISSUE TITLE
Minor, low priority improvement

### ISSUE THREAD

**Issue by renox92** [happypandax/happypandax#160]
What about adding something like a synopsis field, but only visible in editing mode, so that people could populate it with searchable text? I remember how 10 year old tutorials on making web pages said something like "add a buch of keywords here so that google will pick your page up", the idea would be similar here. Just fill it up with loose description, story elements, maybe keywords that are not worth creating a tag for etc, so that when you can't find specific doujin you could include that field in search. Maybe make it possible to look just at that field when searching, so that it won't look for matches in tags or titles.

For example, I could write something like "girl saves a guy from drowning", and easily find it later even If I don't remember any tags. I suggest making this field hidden, because I kinda expect to be bulky and messy most of the time. Like in the same example I could add "sea, ocean, underwater" and a bunch of other words, for, you know, being able to find it while not using the exact words I used in synopsis.

Edit: Maybe it would be better to display the contents of that text field over cover pages when searching within said field, like a half transparent overlay, or some other solution that would allow glancing over many descriptions quickly.

**Comment by twiddli** [comment]
Hi,
This is already possible.
When editing a gallery, you can set a description:
![billede](https://user-images.githubusercontent.com/11841002/64925612-a5313100-d7f3-11e9-87fe-ac42166370a9.png)
This description is searchable with the `description` namespace.
