### ISSUE TITLE
Unable to use filters in sqlite

### ISSUE THREAD

**Issue by Sebleux** [happypandax/happypandax#161]
**Describe the bug**
I cannot figure out how to use the filters. I searched in the documentation but there is no example of what to put in the "Search query" field. For example I tried `tags:none` and `-tags:none` with no results. I can only manually add galleries to filters.

**To Reproduce**
1. Go to Management
2. Make a new filter
3. Filter creates but contains no matching galleries

**Logs**
I don't know if that's the cause but there is some errors when using filters :
[error.log](https://github.com/happypandax/happypandax/files/3643411/error.log)

**Environment:**
 - OS: Win 10
 - Chrome 77
 - HPX Version 11.2
 - sqlite

**Comment by twiddli** [comment]
I'm positive this was fixed in `v0.12.0`, if not, please re-open.
