### ISSUE TITLE
I don't know why it can't get information from e-hentai !!!

### ISSUE THREAD

**Issue by fanglangxinghai** [happypandax/happypandax#163]
**Describe the bug**
For example, most of manga i have ( which downloaded from e-hentai ) can't get **_tags_** from e-hentai. It just get the   Artist,Series,Pages from the title itself.

I don't know why some manga can get tags, and most of manga can not get tags.Every manga has original Japanese title since they are downloaded from e-hentai/exhentai.

I have installed two plugins, EHentai Login and EHentai Metadata.

Besides，since my country has banned a lot of sites like google,youtube,e-hentai , i use shadowsocksr ( proxy ) to connect e-hentai on the chrome. I don't know if it has influence  when using happypandax ,since i have used global mode of shadowsocksr when using happypandax.
 

**Screenshots**
i don't know how to update picture.i hope you have understood my problem.
 
**Environment:**
 - OS: windows
 - Browser and browser version : chrome  77.0.3865.90 （64 bit）
 - HPX Version : 0.11.2.win

**Comment by twiddli** [comment]
Hello, after querying for metadata you can check if it succeeded by opening a gallery's item log:
![billede](https://user-images.githubusercontent.com/11841002/66348490-f5189900-e956-11e9-8a36-dc8898d4cee2.png)
 
Can you show me the item log for one of your galleries that can't get tags?
Additionally, there is a file named `plugin.log` in the folder where the EHentai Metadata plugin is located. Can you give me that file?

**Comment by twiddli** [comment]
Hello, after querying for metadata you can check if it succeeded by opening a gallery's item log:
![billede](https://user-images.githubusercontent.com/11841002/66348490-f5189900-e956-11e9-8a36-dc8898d4cee2.png)
 
Can you show me the item log for one of your galleries that can't get tags?
Additionally, there is a file named `plugin.log` in the folder where the EHentai Metadata plugin is located. Can you give me that file?

**Comment by twiddli** [comment]
> I think it's better to add a function to let user know If the getting-tag process is working.For Example, make a progress bar with it.

Please create a new issue with this suggestion
