### ISSUE TITLE
Error starting in Ubuntu

### ISSUE THREAD

**Issue by wickedwzrd** [happypandax/happypandax#164]
I am unable to start the application with `./happypandx` and `./happypandax_gui`. I'm using postgresql instead of sqlite.

**Logs**
[error.log](https://github.com/happypandax/happypandax/files/3721257/error.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/9831909/66708891-2f52b380-ed26-11e9-9a22-7e2d3a74ff78.png)

**Environment:**
 - OS: Ubuntu 19.04
 - Firefox 69.0.2
 - HPX Version 0.11.2

**Comment by twiddli** [comment]
Hi, could you try and start in debug mode for the `debug.log`?

**Comment by wickedwzrd** [comment]
Sorry for the delay but I have attached my `debug.log`
[debug.log](https://github.com/happypandax/happypandax/files/3722816/debug.log)

**Comment by twiddli** [comment]
That log isn't actually telling me anything useful. Are you closing the program too early?

**Comment by wickedwzrd** [comment]
No and I just saw that this issue only occurs when I use postgres as my DB. I switched back to sqlite and it started perfectly fine. The only reason I wanted to switch to postgres was due to an error that I get when trying to scan my folder to add to my collection.

**Comment by wickedwzrd** [comment]
I wanted to use postgres since the docs mentioned that sqlite doesn't handle large DB's very well, and I have a large amount of comics that I wanted to scan in.

**Comment by twiddli** [comment]
I'm a little confused.
The debug.log you sent me doesn't even reach to the point of the error you got in your first post. So either you're closing the program too early before it reaches to that point, or you're encountering another kind of error?

> The only reason I wanted to switch to postgres was due to an error that I get when trying to scan my folder to add to my collection.

What was the error?
If you don't actually tell me then it might never get fixed.

**Comment by wickedwzrd** [comment]
I included a video for sqlite and postgres running, with the changed `config.yaml`
Link for both videos: https://imgur.com/a/lWZQ0ss
```
What was the error?
If you don't actually tell me then it might never get fixed.
```

Regarding this error it was due to the was I inputed the folder location. I noticed that by default a `\` is added to a folder location. So after I removed one from the location it worked fine. However with the large size of my folder, when I tried to scan it after reading the folder then going through and trying to import everything it pretty much crashed after 940 folders or so. The scan stopped responding.

**Comment by wickedwzrd** [comment]
Ok so I figured out the problem of why it wasn't connecting to the postgres DB. The name within the config was incorrect so it wasn't able to establish a connection. 
My next question would be what I mentioned in my earlier comment: Is there a buffer limit of how many comics can be added through the `scan for new galleries` tab ?

**Comment by twiddli** [comment]
There has been some issues with the client dropping the connection during the gallery scan, causing the client to lose progress (while the scan is in fact still running on the server). As a quick workaround, I added a way to limit how many galleries was to be scanned and added with the limit and offset inputs.

**Comment by twiddli** [comment]
By the way, what font are you using in that screenshot? I like it.

**Comment by wickedwzrd** [comment]
Sorry for the late response but monospace regular, the default ubuntu font
