### ISSUE TITLE
Thumbnails and Pages do not show

### ISSUE THREAD

**Issue by Amorins1** [happypandax/happypandax#167]
I tryed other methods to see if it will work but this error also popped up 
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: gallery_userdata.user_id
[SQL: INSERT INTO gallery_userdata (times_read, rating, _properties, last_updated, user_id, parent_id) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: (0, 1.0, '{}', '2019-10-24 09:38:14.868408', None, 2)]

Its the latest update and before it was applied everything was working 
![Capture](https://user-images.githubusercontent.com/56958929/67474245-ff01f380-f608-11e9-941c-1682efce31cf.PNG)

Not sure what else to do but help of any kind would be great, thanks for your time

**Comment by Killuas** [comment]
Have the exact same probably with galleries showing up empty. The data still obviously exists somewhere, because scanning my local files does not cause the missing galleries to show up.

![image](https://user-images.githubusercontent.com/18124782/67547769-d8999200-f6b4-11e9-98c3-9e8b73aa94a1.png)

**Comment by TindalosHound** [comment]
I can verify that. Getting the same problem here.

**Comment by twiddli** [comment]
Hello, could any of you provide any logs? Preferably a debug.log

**Comment by Amorins1** [comment]
Heres mine 
[debug.log](https://github.com/happypandax/happypandax/files/3773686/debug.log)

**Comment by Killuas** [comment]
I don't seem to have any debug folder in my logs.

**Comment by twiddli** [comment]
I also need an `error.log`

**Comment by Amorins1** [comment]
aye aye
[error.log](https://github.com/happypandax/happypandax/files/3780947/error.log)

**Comment by twiddli** [comment]
Fixed in `v0.12.3`.
I hope you guys have a backup database available because this error occurred because pages, tags and more got erroneously deleted from the database upon migration.
Automatic backups has been a part of HPX since `v0.10.0` and by default a backup would be made every 3 days in a folder called `backups`
