### ISSUE TITLE
Unable to add any galleries

### ISSUE THREAD

**Issue by flimi** [happypandax/happypandax#168]
I recently did a full reinstall and whenever i attempt to add a gallery from a zip or the like I get the error '[HappyPandaError100]: NotImplementedError(Value deserializing for this descriptor has not been implemented yet: Artist.preferred_name)' and the gallery is not added. I really have no idea what to do here

**Comment by twiddli** [comment]
What version of HPX are you on?
What about any logs?
OS?

**Comment by flimi** [comment]
I am on Windows 10 Enterprise Version 1803. 
Below are the error logs from when I attempt to add a gallery:

> Oct-10 20:41:04--WARNING happypanda.migrate: Failed to remove data/internals.db. Please remove it yourself. 
> Oct-10 20:43:02--ERROR  [command].happypanda.core.services: Command AddItem(116) raised an exception 
> Traceback (most recent call last):
>   File "site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
>   File "site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
> sqlite3.IntegrityError: NOT NULL constraint failed: gallery_userdata.user_id
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "happypanda\core\services.py", line 451, in _callback_wrapper
>   File "src\gevent\greenlet.py", line 683, in gevent._greenlet.Greenlet.get
>   File "src\gevent\greenlet.py", line 317, in gevent._greenlet.Greenlet._raise_exception
>   File "site-packages\gevent\_compat.py", line 47, in reraise
>   File "src\gevent\greenlet.py", line 766, in gevent._greenlet.Greenlet.run
>   File "happypanda\core\db.py", line 4092, in wrapper
>   File "happypanda\core\command.py", line 103, in _run
>   File "happypanda\core\command.py", line 359, in _main_wrap
>   File "happypanda\core\commands\database_cmd.py", line 1283, in main
>   File "happypanda\core\async_utils.py", line 347, in get
>   File "src\gevent\greenlet.py", line 709, in gevent._greenlet.Greenlet.get
>   File "src\gevent\greenlet.py", line 317, in gevent._greenlet.Greenlet._raise_exception
>   File "site-packages\gevent\_compat.py", line 47, in reraise
>   File "src\gevent\greenlet.py", line 766, in gevent._greenlet.Greenlet.run
>   File "site-packages\gevent\pool.py", line 88, in apply_cb
>   File "site-packages\gevent\pool.py", line 159, in apply
>   File "src\gevent\event.py", line 268, in gevent._event.AsyncResult.get
>   File "src\gevent\event.py", line 296, in gevent._event.AsyncResult.get
>   File "src\gevent\event.py", line 286, in gevent._event.AsyncResult.get
>   File "src\gevent\event.py", line 266, in gevent._event.AsyncResult._raise_exception
>   File "site-packages\gevent\_compat.py", line 47, in reraise
>   File "site-packages\gevent\threadpool.py", line 281, in _worker
>   File "happypanda\core\async_utils.py", line 453, in wrapper
>   File "happypanda\core\async_utils.py", line 435, in cleanup_wrapper
>   File "happypanda\core\commands\database_cmd.py", line 1188, in _add_to_db
>   File "happypanda\core\commands\database_cmd.py", line 1139, in _add_item
>   File "site-packages\sqlalchemy\orm\session.py", line 1027, in commit
>   File "site-packages\sqlalchemy\orm\session.py", line 494, in commit
>   File "site-packages\sqlalchemy\orm\session.py", line 473, in _prepare_impl
>   File "site-packages\sqlalchemy\orm\session.py", line 2459, in flush
>   File "site-packages\sqlalchemy\orm\session.py", line 2597, in _flush
>   File "site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
>   File "site-packages\sqlalchemy\util\compat.py", line 153, in reraise
>   File "site-packages\sqlalchemy\orm\session.py", line 2557, in _flush
>   File "site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
>   File "site-packages\sqlalchemy\orm\unitofwork.py", line 589, in execute
>   File "site-packages\sqlalchemy\orm\persistence.py", line 245, in save_obj
>   File "site-packages\sqlalchemy\orm\persistence.py", line 1138, in _emit_insert_statements
>   File "site-packages\sqlalchemy\engine\base.py", line 988, in execute
>   File "site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
>   File "site-packages\sqlalchemy\engine\base.py", line 1107, in _execute_clauseelement
>   File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
>   File "site-packages\sqlalchemy\engine\base.py", line 1466, in _handle_dbapi_exception
>   File "site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
>   File "site-packages\sqlalchemy\util\compat.py", line 152, in reraise
>   File "site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
>   File "site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
> sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: gallery_userdata.user_id
> [SQL: INSERT INTO gallery_userdata (times_read, rating, _properties, last_updated, user_id, parent_id) VALUES (?, ?, ?, ?, ?, ?)]
> [parameters: (0, 0.0, '{}', '2019-10-25 19:43:02.405731', None, 1)]
> (Background on this error at: http://sqlalche.me/e/gkpj)

**Comment by twiddli** [comment]
The actual log files would've been more helpful.
How are you trying to add a gallery? Through the scanner?

**Comment by flimi** [comment]
Sorry I misunderstood. I tried adding through both the 'new' function and the scan function, neither of which worked, though only the 'new' gave an error.
[error.log](https://github.com/happypandax/happypandax/files/3775895/error.log)
[activity.log](https://github.com/happypandax/happypandax/files/3775896/activity.log)

**Comment by twiddli** [comment]
fixed in `v0.12.3`
