### ISSUE TITLE
After upgrading to 0.12.2, I receive an error after database update.

### ISSUE THREAD

**Issue by ARockyRock** [happypandax/happypandax#170]
**Describe the issue**
The problem occurs after upgrading from 0.11.2 to 0.12.0 then to 0.12.2. What happens is after the server goes for a database update, it leaves me with `>: Could not locate a bind configured on mapper mapped class Life->life, SQL expression or this Session` and stops the server afterwards.
I have since downgraded back to 0.11.2 and the server runs perfectly fine.
I have also made a whole new blank DB and see if it'd work and still the error shows up.

**To Reproduce**
1. Have a PostgreSQL database using HPX 0.11.2
2. Let it auto-update or perform manual update (I did both)
3. Start the server
4. Receive error: 
`>: Could not locate a bind configured on mapper mapped class Life->life, SQL expression or this Session`

**Logs**
[error.log](https://github.com/happypandax/happypandax/files/3777376/error.log)

**Environment:**
 - OS: Windows 10 ver. 1903
 - Database: PostgreSQL ver. 11.5
 - HPX Version 0.12.2

**Comment by twiddli** [comment]
I'm positive i fixed this in `v0.12.3`
