### ISSUE TITLE
Postgres sorting by rating causes database error in 0.12.2

### ISSUE THREAD

**Issue by Waiifu** [happypandax/happypandax#172]
**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. Go to sort by Rating (asc, or desc doesn't matter)
3. See error

**Logs**
[error.log](https://gist.github.com/Waiifu/27f9269e8be45428ecb5a220e0762242)

**Screenshots**
https://i.imgur.com/0MSfhm5.png

**Environment:**
 - Linux
 - FF70.0b8
 - HPX Version 0.12.2

**Additional context**
Sorting by rating on SQLite seems to also not work. I'll probably make a separate issue for it later.

**Comment by twiddli** [comment]
fixed in `v0.12.3`
