### ISSUE TITLE
Migrating database ratings to 0.12.2

### ISSUE THREAD

**Issue by Waiifu** [happypandax/happypandax#173]
**Describe the issue**
All of my personal ratings get cleared upon the 0.12.2 update, due to how ratings are changed to be handled per-user. 

I'm not entirely sure if this is intended or not, if it is, then I can make a feature-request (or change this?) to one.

**To Reproduce**
1. Update to 0.12.2

**Expected behavior**
Not entirely sure.

**Environment:**
 - Linux
 - FF70.0b8
 - HPX Version 0.12.2

**Comment by twiddli** [comment]
Hello, they were not cleared but were instead only associated with the default user. I can make it so all users get them.

**Comment by twiddli** [comment]
added in `v0.12.3`
