### ISSUE TITLE
Revision not found when using postgres from 11.2 to 12.3

### ISSUE THREAD

**Issue by rwchunk** [happypandax/happypandax#174]
**Describe the issue**
Unable to start server

**To Reproduce**
1. Setup a postgres database with HPX 11.2
2. Start the server and use 'update and restart', updates to 12.3
3. Encounter error on server start after updating

**Expected behavior**
Server starts without error.

**Logs**
[debug.log](https://github.com/happypandax/happypandax/files/3786350/debug.log)
[error.log](https://github.com/happypandax/happypandax/files/3786351/error.log)

**Environment:**
 - OS: Windows 10 LTSC
 - HPX Version 11.2 -> 12.3
 - Postgres 11.5

**Comment by twiddli** [comment]
Hi, this is so weird. Are you able use 11.2 with no problems using this database?

**Comment by ARockyRock** [comment]
As you would predict I am also having the same issue. My database does work in 11.2.
I'll drop my logs off although they'll probably be identical rw's.
[debug.log](https://github.com/happypandax/happypandax/files/3792437/debug.log)
[error.log](https://github.com/happypandax/happypandax/files/3792439/error.log)

**Comment by rwchunk** [comment]
Yeah. I tested with fresh install and a new database. The only thing that has changed is that I installed postgres 12 but thats probably not related.

**Comment by twiddli** [comment]
Okay, so this does not work you say?
- Make sure the HPX 0.11.2 has no influence of 0.12 by installing it in a separate place
- Run the database with HPX 0.11.2 without any error
- Close and update to latest HPX 0.12 either by overwriting the files of HPX 0.11.2 with 0.12 or by letting it auto-update
- Run the database with HPX 0.12

**Comment by rwchunk** [comment]
Yep. Didn't use the installer, just extracted to a new folder.

**Comment by twiddli** [comment]
I see that both of you are on windows.
Can any of you try this release and see if it got fixed?
https://github.com/happypandax/happypandax/releases/tag/v0.12.4-pre

**Comment by rwchunk** [comment]
it started for me, here's the logs just in case
[error.log](https://github.com/happypandax/happypandax/files/3799715/error.log)
[activity.log](https://github.com/happypandax/happypandax/files/3799716/activity.log)

**Comment by twiddli** [comment]
could you also try #175?

**Comment by twiddli** [comment]
I just updated the archive, could you try again?
https://github.com/happypandax/happypandax/releases/tag/v0.12.4-pre
Hopefully no errors pops up this time.

**Comment by rwchunk** [comment]
Repeating the process for this issue created another error.
![image](https://user-images.githubusercontent.com/19255865/68061993-959f7600-fcd5-11e9-97a4-94ec04017c53.png)
[activity.log](https://github.com/happypandax/happypandax/files/3799897/activity.log)
[error.log](https://github.com/happypandax/happypandax/files/3799898/error.log)

**Comment by twiddli** [comment]
Okay, I think this should do it.
https://github.com/happypandax/happypandax/releases/tag/v0.12.4-pre

**Comment by rwchunk** [comment]
The test was successful. GJ

**Comment by twiddli** [comment]
fixed in `0.12.4`
