### ISSUE TITLE
Metadata search query customization

### ISSUE THREAD

**Issue by rwchunk** [happypandax/happypandax#178]
**Is your feature request related to a problem? Please describe.**
There are some cases where I know that the items being queried for metadata can be searched with a certain query, and this can be applied to a group of queries.
For example, certain galleries won't appear if the published comic is included in the search query text. Or, certain searches may have better accuracy if I include certain terms which haven't been indicated elsewhere within HPX. Basically, if there was information excluded or lost when importing or otherwise, can be resolved by using metadata search to find and apply tags.

**Describe the solution you'd like**
It's probably possible to change the query by editing the scripts, but I'd like for there to be an option in the client-side to edit the query. Also on a per-plugin basis.

**Describe alternatives you've considered**
This could've been resolved if I had included the term on import, however, there is still the issue that the search query can be too specific. Such that the search result doesn't include the correct gallery because it has less information than is recorded in HPX - this happens often where HPX has the published comic and other information to search by but panda.chaika does not.

**Comment by twiddli** [comment]
Hello, you're right, there needs to be an easy way to configure that client-side.
In case you haven't seen it, EHentai and nhentai metadata plugins have the `search_query` options to do just that.
https://github.com/happypandax/plugins/tree/master/plugins/EHentai%20Metadata

**Comment by rwchunk** [comment]
Thanks for the help, that is the way.
