### ISSUE TITLE
 Ampersand in circles is translated as "&amp;"

### ISSUE THREAD

**Issue by nonamethanks** [happypandax/happypandax#182]
**Describe the issue**
Ampersand in circles is translated as "`&amp;`"
Probably happens with other fields too, haven't tested.

**To Reproduce**
Just download a gallery from any circle like https://exhentai.org/tag/group:oboro+and+tempo+gensui+dou and fetch metadata.

**Screenshots**
![image](https://user-images.githubusercontent.com/12946050/68079912-e0aeab80-fdf1-11e9-8542-034fcb1727dc.png)

**Environment:**
Linux, latest version

**Comment by twiddli** [comment]
Fixed in `v0.13.0`
