### ISSUE TITLE
[Request] Add Fakku site in fetching metadata

### ISSUE THREAD

**Issue by YukiSakuma** [happypandax/happypandax#19]
I know there's still no binary release and Fakku is not supported in HP but I am hoping this site can be added in HPX

**Comment by Pewpews** [comment]
Hi, I'm not too keen on implementing anything Fakku related.
With HPX's plugin system (*not finished yet*) however, it should be possible to implement such a metadata fetcher (not saying that I will).

**Comment by YukiSakuma** [comment]
May I know why? The reason for me is because adding them tags manually would be tedious as I have tons of them.

**Comment by Pewpews** [comment]
Because I don't use fakku myself, and iirc panda.chaika already has the tags neatly organized for most of the galleries.
![255035991855857674](https://user-images.githubusercontent.com/11841002/27644361-9c0e9354-5c23-11e7-984d-96e5e5169053.jpg)

**Comment by Zuescho** [comment]
Also just so you know they really do not like anyone messing with there stuff.
https://doujindownloader.com/tag/fakku-net/
So it would be better to use other sources.

**Comment by YukiSakuma** [comment]
Yeah panda chaika is really an excellent site, but most or some of the 'galleries' there are not tagged though since the last two batches or it might be it's just slow to add the tags.

**Comment by YukiSakuma** [comment]
How about adding hentai.cafe in fetching metadata?

**Comment by Zuescho** [comment]
he will kill you for trying this, hentai.cafe has huge problems with scrapers downloading everything from it.
If anything you could take nhentai into the mix.

**Comment by Pewpews** [comment]
Metadata retrieval from Fakku will not be implemented. For other sites, please open new issues.
