### ISSUE TITLE
HPX v0.12.4 gallery add error

### ISSUE THREAD

**Issue by waz1500** [happypandax/happypandax#191]
**Describe the issue**
Unable to add any galleries in HappyPanda X v0.12.4. Console results in "An error occurred when adding item '"

**To Reproduce**
1. Fresh install of HappyPanda X v0.12.4. Zip extracted
2. Load up the client and log in as guest
3. Enable FileMetadata plugin (Since I use hdoujin info files for metadata)
4. Add galleries. Simple folder scan whilst enabling transparent folder option.
5. See error and white screen. 

**Expected behavior**
Galleries should add fine. Last working version is HappyPanda X v0.12.2. 
**Logs**
[logs.zip](https://github.com/happypandax/happypandax/files/3814787/logs.zip)

**Screenshots**
![hpxerror](https://user-images.githubusercontent.com/17833884/68305693-05c84600-00a0-11ea-8c8f-82a195922a8a.jpg)

**Environment:**
 - OS: Windows 10
 - Version 78.0.3904.87 (Official Build) (64-bit)
 - HappyPanda X v0.12.4

**Anything Else**
My test collection folder has only about 250 galleries in it. Same error occurs in HPX v0.12.3.

**Comment by twiddli** [comment]
Hello, new in 0.12, it's now not possible to add galleries when logged in as an unregistered guest anymore. I forgot all about this so I didn't manage to make a proper error message.

**Comment by waz1500** [comment]
Thanks for the clarification twiddli. I didn't know about the limitations of the guest account.  I tested with the default super user account and all is working fine.

Feel free to close this issue. If you do want to add a error message, you can use this ticket as a reminder. 
Cheers!

**Comment by twiddli** [comment]
better user permission control is now in `v0.13.0`
