### ISSUE TITLE
Tag popup goes out of view sometimes

### ISSUE THREAD

**Issue by nonamethanks** [happypandax/happypandax#192]
**Describe the issue**
Due to the popup being loaded before the tag description, sometimes when the description is fetched it expands the popup outside of the visible view, which means you can't search a tag from a gallery's tags because the button is outside the visible area.

**Screenshots**
![image](https://user-images.githubusercontent.com/12946050/68487311-1ebd2c80-0243-11ea-8af9-51f5ae3f1cd8.png)

**Environment:**
Chrome

**Comment by twiddli** [comment]
tried to improve this in `v0.13.0`
