### ISSUE TITLE
Scan only for new galleries not working

### ISSUE THREAD

**Issue by NO-ob** [happypandax/happypandax#194]
When scanning a directory for galleries galleries already imported will be imported again resulting in duplicates

1. Goto Add
2. Goto Scan tab
4. Scan a directory
3. Galleries that already exist will be added even with scan only for new galleries checked

**Expected behavior**
Only new galleries to be imported

**Environment:**
 - OS: Debian
 - Firefox 68
 - v0.12.4

**Comment by zatsuna** [comment]
I still get this bug in 0.13.1.

**Comment by twiddli** [comment]
should be fixed in `v0.13.2`
