### ISSUE TITLE
ERR_CONNECTION_REFUSED error message when trying to access the webclient

### ISSUE THREAD

**Issue by MeiMei3** [happypandax/happypandax#195]
As the title says, i get the following error message when trying to access the webclient from either my phone or pc. HPX worked fine for 2 visits-ish until this happened. 
![4CSArqu](https://user-images.githubusercontent.com/52470208/72663705-15e49600-39fe-11ea-92e8-3709034e2998.png)
Help would be much appreciated

**Comment by twiddli** [comment]
More info about your setup is needed.
Are you using HPX Desktop?
Can the HPX server start without any errors popping up?
What are your server settings?

**Comment by MeiMei3** [comment]
> More info about your setup is needed.
> Are you using HPX Desktop?
> Can the HPX server start without any errors popping up?
> What are your server settings?

Yeah sorry about that. Im using HPX desktop and it starts fine without any errors. My server settings are below 
![nlensyT](https://user-images.githubusercontent.com/52470208/72690927-c26f6680-3b29-11ea-8bc0-bdf52c4e216a.png)
![klMkvQA](https://user-images.githubusercontent.com/52470208/72690928-c3a09380-3b29-11ea-8c96-c665d6d665a3.png)

**Comment by twiddli** [comment]
Settings looks alright.
I understand that it works as it should when using HPX Desktop?
Can you enable debug mode `core -> debug`? Then try running HPX server and connecting again through your browser. Provide me with the generated `debug.log`.

**Comment by MeiMei3** [comment]
Yeah, HPX desktop works perfectly. 
Heres the log 
Jan-01 16:38:00--INFO   happypanda.common.hlogger: debug.log created at E:\Weebshit2\doujin\HappyPandaX\logs\debug.log 
Jan-01 16:38:00--INFO   [core].happypanda.common.config: Loading existing configuration from E:\Weebshit2\doujin\HappyPandaX\config.yaml 
Jan-01 16:38:00--DEBUG  [server].happypanda.core.server: Loaded 94 Interface functions 
Jan-01 16:38:00--INFO   happypanda.main: HPX START 
Jan-01 16:38:00--INFO   happypanda.main: Version: 0.12.4 
Jan-01 16:38:00--INFO   happypanda.main: DB Version: 0.8.0 
Jan-01 16:38:00--INFO   happypanda.main: Web Version: 0.12.0 
Jan-01 16:38:00--INFO   happypanda.main: DEBUG MODE ENABLED 
Jan-01 16:38:00--INFO   happypanda.main: ('AMD64', 'Windows-10-10.0.18362-SP0') 
Jan-01 16:38:00--INFO   happypanda.migrate: Applying migrations 
Jan-01 16:38:00--INFO   [database].happypanda.core.db: Using sqlite database 
Jan-01 16:38:00--DEBUG  [database].happypanda.core.db: Checking for database update 
Jan-01 16:38:00--INFO   alembic.runtime.migration: Context impl SQLiteImpl.
Jan-01 16:38:00--INFO   alembic.runtime.migration: Will assume non-transactional DDL.
Jan-01 16:38:00--DEBUG  [database].happypanda.core.db: Database BASE revision: ('6ab71d7090de', ) 
Jan-01 16:38:00--DEBUG  [database].happypanda.core.db: Database current revision: ('5ec76281dee9', ) 
Jan-01 16:38:00--DEBUG  [database].happypanda.core.db: Database HEAD revision: ('5ec76281dee9', ) 
Jan-01 16:38:00--INFO   [database].alembic.env: Migrating database main
Jan-01 16:38:00--INFO   alembic.runtime.migration: Context impl SQLiteImpl.
Jan-01 16:38:00--INFO   alembic.runtime.migration: Will assume non-transactional DDL.
Jan-01 16:38:00--DEBUG  [database].happypanda.core.db: Using DB Version: 0.8.0 
Jan-01 16:38:00--DEBUG  [database].happypanda.core.db: Succesfully initiated database 
Jan-01 16:38:04--DEBUG  [command].happypanda.core.services: Started scheduler service: scheduler 
Jan-01 16:38:04--DEBUG  [command].happypanda.core.services: Service (async) added command: CheckUpdate (100) 
Jan-01 16:38:04--INFO   happypanda.main: Initiating background CheckUpdate 
Jan-01 16:38:04--INFO   happypanda.main: Initiating background auto BackupApplication 
Jan-01 16:38:04--DEBUG  [command].happypanda.core.services: Service (async) added command: TrashSweeper (103) 
Jan-01 16:38:04--INFO   happypanda.main: Initiating background TrashSweeper 
Jan-01 16:38:04--INFO   happypanda.main: Initiating background CacheCleaner 
Jan-01 16:38:04--DEBUG  [command].happypanda.core.services: Service (task) added command: CacheCleaner (105) 
Jan-01 16:38:04--INFO   happypanda.main: Initiating background download CacheCleaner 
Jan-01 16:38:04--DEBUG  [command].happypanda.core.services: Service (task) added command: CacheCleaner (106) 
Jan-01 16:38:04--INFO   happypanda.main: Initiating background thumbnail CacheCleaner 
Jan-01 16:38:04--DEBUG  [command].happypanda.core.services: Service (task) added command: CacheCleaner (107) 
Jan-01 16:38:04--INFO   happypanda.main: Initiating background pages CacheCleaner 
Jan-01 16:38:04--DEBUG  [command].happypanda.core.services: Service (task) added command: CacheCleaner (108) 
Jan-01 16:38:04--INFO   happypanda.main: Initiating background temp CacheCleaner 
Jan-01 16:38:04--DEBUG  [command].happypanda.core.services: Service (task) added command: CacheCleaner (109) 
Jan-01 16:38:04--INFO   happypanda.main: Initiating filters updater UpdateFilters 
Jan-01 16:38:04--DEBUG  [command].happypanda.core.services: Service (async) added command: UpdateFilters (110) 
Jan-01 16:38:04--DEBUG  [command].happypanda.core.services: Service (task) added command: UpdateFilters (111) 
Jan-01 16:38:04--INFO   [server].happypanda.core.fairy: Configuring redis server connection 127.0.0.1:7009:0 with password(False) 
Jan-01 16:38:04--DEBUG  [server].happypanda.core.fairy: Initialising redis keys 
Jan-01 16:38:06--DEBUG  [server].happypanda.core.fairy: Redis server is already up: False 
Jan-01 16:38:06--INFO   [server].happypanda.core.fairy: Starting builtin redis server... 
Jan-01 16:38:06--DEBUG  [server].happypanda.core.fairy: Redis server process status: None 
Jan-01 16:38:06--INFO   [server].happypanda.core.fairy: Waiting on redis for maximum 20 seconds... 
Jan-01 16:38:08--DEBUG  [server].happypanda.core.fairy: Redis server final ping result: 1 
Jan-01 16:38:08--DEBUG  happypanda.main: Configured caches 
Jan-01 16:38:08--INFO   happypanda.main: Starting webserver... (0.0.0.0:7008) 
Jan-01 16:38:08--DEBUG  [command].happypanda.core.command: Emitting event 'InitApplication.before_plugins' with args '()' - '{}' 
Jan-01 16:38:08--INFO   [plugin].happypanda.core.plugins: Loading plugins from path: plugins 
Jan-01 16:38:08--INFO   [plugin].happypanda.core.plugins: Loading 8 plugins 
Jan-01 16:38:08--DEBUG  [command].happypanda.core.command: Emitting event 'InitApplication.after_plugins' with args '()' - '{}' 
Jan-01 16:38:08--DEBUG  [plugin].happypanda.core.plugins: Calling all handlers (default: True) for 'InitApplication.after_plugins' [capture=False] 
Jan-01 16:38:08--DEBUG  [plugin].happypanda.core.plugins: Calling all handlers (default: True) for 'InitApplication.after_plugins' [capture=False] 
Jan-01 16:38:08--DEBUG  [command].happypanda.core.services: Service (async) added command: UpdatePlugin (112) 
Jan-01 16:38:08--INFO   happypanda.main: Initiating background UpdatePlugin 
Jan-01 16:38:08--DEBUG  [command].happypanda.core.command: Running command: InitApplication 
Jan-01 16:38:08--DEBUG  [command].happypanda.core.command: Calling main function of command: InitApplication 
Jan-01 16:38:08--DEBUG  [command].happypanda.core.command: Emitting event 'InitApplication.init' with args '()' - '{}' 
Jan-01 16:38:08--DEBUG  [plugin].happypanda.core.plugins: Calling all handlers (default: True) for 'InitApplication.init' [capture=False] 
Jan-01 16:38:08--DEBUG  [plugin].happypanda.core.plugins: Calling all handlers (default: True) for 'InitApplication.init' [capture=False] 
Jan-01 16:38:08--DEBUG  [command].happypanda.core.command: Finished running command: InitApplication 
Jan-01 16:38:08--INFO   [server].happypanda.core.server: Starting server... (0.0.0.0:7007) 
Jan-01 16:38:08--WARNING [server].happypanda.core.server: Failed to start server because the address is already in use. Ensure that no other application or HPX isntances are using the same address 
Jan-01 16:38:08--DEBUG  [command].happypanda.core.command: Calling command handler <CoreFS.archive_formats> 
Jan-01 16:38:08--INFO   happypanda.common.hlogger: Logger shutting down.

**Comment by twiddli** [comment]
Hi, it says ```Failed to start server because the address is already in use. Ensure that no other application or HPX isntances are using the same address```.

Make sure that port 7007 and 7008 are free.

**Comment by MeiMei3** [comment]
> Hi, it says `Failed to start server because the address is already in use. Ensure that no other application or HPX isntances are using the same address`.
> 
> Make sure that port 7007 and 7008 are free.

How do i do that? Sorry I'm bad with this stuff

**Comment by twiddli** [comment]
Restart your computer.
Make sure only one instance of HPX server is running.
If you're using HPX Desktop, make sure to connect it with the existing HPX server by putting in `localhost:7007` and `localhost:7008`

**Comment by MeiMei3** [comment]
So where should i put `localhost:7007` and `localhost:7008`? I did get this error message though and I'm not getting the ERR_CONNECTION_REFUSED error anymore

**Comment by twiddli** [comment]
![billede](https://user-images.githubusercontent.com/11841002/72981869-1a35f800-3dde-11ea-8368-5180a43819b8.png)

**Comment by twiddli** [comment]
As soon as you open up HappyPanda X Desktop

**Comment by MeiMei3** [comment]
well I guess I haven't been using the desktop app then. I also have no idea how to open this

**Comment by twiddli** [comment]
You're on windows, right?
Press `Win + R` -> type `resmon.exe` -> Click on the `Network` tab -> Expand the `Listening ports` tabs -> sort by `port` -> find `7007` and `7008` and which process is using them and kill them.

Or alternatively, just change `7007` and `7008` to something else in the HPX settings.

**Comment by MeiMei3** [comment]
Only HPX is using those ports. I tried changing them but didn't work out.
![EWA6YWA](https://user-images.githubusercontent.com/52470208/73138032-cf7ae100-4066-11ea-965e-f82b282a4970.png)
I'm getting a different error now though

**Comment by twiddli** [comment]
Just restart the server

**Comment by MeiMei3** [comment]
Ah, well it still refuses to connect even though the ports should be free

**Comment by twiddli** [comment]
So weird, how did you restart?

**Comment by MeiMei3** [comment]
I restarted my PC and then opened the program again. After it gave me the error message I went to check if the ports are free and they were.

**Comment by twiddli** [comment]
Can you try and message me here https://gitter.im/Pewpews/happypandax

**Comment by twiddli** [comment]
Please reopen if the issue persists.
