### ISSUE TITLE
DetachedInstanceError when browsing content

### ISSUE THREAD

**Issue by waz1500** [happypandax/happypandax#199]
**Describe the issue**
When image browsing back and forth on a manga this error will popup. 
Using SQL database but error also appears when using Postgress 11. Similar to issue https://github.com/happypandax/happypandax/issues/108

```[DatabaseError|300]: DetachedInstanceError(Parent instance <Page at 0x153f33ce75c0> is not bound to a Session; deferred load operation of attribute 'last_updated' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3))```

**To Reproduce**
1. Click on a manga. 
2. Start browsing images. Go back and forth etc. 
3. See error

**Expected behavior**
Images being loaded on browser without the error. Could have something to do with my content being in .zip?

**Logs**
[debug.log](https://github.com/happypandax/happypandax/files/4155530/debug.log)

**Environment:**
 - OS: latest hpx Docker and using latest chrome browser to view
 - Version 79.0.3945.130 (Official Build) (64-bit)
 - HPX Version 0.12.4

**Comment by twiddli** [comment]
Yes, this is confirmed

**Comment by twiddli** [comment]
should be fixed in `v0.13.0`
