### ISSUE TITLE
Unknown error, can't use metadata

### ISSUE THREAD

**Issue by JoGaTo** [happypandax/happypandax#202]
Anybody getting this error:

>: Traceback (most recent call last):
>: File "src\gevent\greenlet.py", line 766, in gevent._greenlet.Greenlet.run
>: File "happypanda\core\db.py", line 4091, in wrapper
>: File "happypanda\interface\meta.py", line 335, in get_command_value
>: happypanda.common.exceptions.CommandError: [CommandError|120]: Command(300) has failed with: [HappypandaError|100]: LoopExit(This operation would block forever
	Hub: <Hub 'ThreadPool Worker Hub' at 0xbb25a28 select pending=0 ref=0 thread_ident=0x19b0>
	Handles:
[])
>: 2020-04-29T00:33:28Z
>: <Greenlet at 0xba67470: get_command_value(command_ids=[300])> failed with CommandError

I've downloaded the latest HPX and can't even get metadata right now.

**Comment by twiddli** [comment]
Please try again in `v0.13.0` and reopen if the issue persists
