### ISSUE TITLE
Some files can not be detected

### ISSUE THREAD

**Issue by uparrows** [happypandax/happypandax#204]
I've copied 1377 files to the content directory , but only 1313 files were detected ,what about the others ?  i'm running hpx by docker on my synology nas  . error log only shows "Jun-06 10:49:21--WARNING [command].happypanda.core.commands.item_cmd: Ignoring path in watched folder because it already exists or is invalid: /content/XXXX" . i've reinstalled hpx 3 times , and unpackaged all zip files and repackaged all of them , still face the problem .

is there any command to refresh gallery manually ?

thanks.

![2](https://user-images.githubusercontent.com/38988286/84496873-5102a100-ace0-11ea-9c2a-619c04593fe7.JPG)

![1](https://user-images.githubusercontent.com/38988286/84496884-552ebe80-ace0-11ea-9d54-588a727198a3.JPG)

**Comment by twiddli** [comment]
what kind of files are they? do they differ from the other files? have you checked they aren't corrupt?

**Comment by dezhaoma** [comment]
> what kind of files are they? do they differ from the other files? have you checked they aren't corrupt?

they are all zip files , same as the others , and i've checked they aren't corrupt . i've tested many times , finally i found if i run hpx after files copied , some files could not be detected  . and if i run hpx first ,then copy files to the content folder ,all of them can be detected , it's wired.

**Comment by 404Fox** [comment]
Is it possible that the filename/path is too long for certain files?

**Comment by uparrows** [comment]
> Is it possible that the filename/path is too long for certain files?

The latest version  works fine，has no such problem ，thanks ！
