### ISSUE TITLE
Inconsistent Search Behaviour.

### ISSUE THREAD

**Issue by anti-beep** [happypandax/happypandax#205]
**Describe the issue**
When I have 'match all terms' enabled

![image](https://user-images.githubusercontent.com/67585977/86001903-e061c100-ba0f-11ea-95e1-1f7e043c5e15.png)

For the search bar, I don't get back the expected results.

For example, if I put in *"futanari"* and *"anal"*

![image](https://user-images.githubusercontent.com/67585977/86002143-3cc4e080-ba10-11ea-8e59-746e774d4713.png)

I only get back a single gallery, containing these tags:

![image](https://user-images.githubusercontent.com/67585977/86002081-20c13f00-ba10-11ea-8afb-e34cb7ad7f9f.png)

However, I have *also* have other galleries with the tags "anal" and "futanari":

![image](https://user-images.githubusercontent.com/67585977/86002232-5d8d3600-ba10-11ea-91c5-536e9ce75f37.png)

and

![image](https://user-images.githubusercontent.com/67585977/86002269-68e06180-ba10-11ea-8533-8599bce8e0ea.png)

But I don't get those back (nor the other galleries containing these tags).

---

If I turn off 'match all galleries' I also experience unexpected behaviour.

If I search just "anal".

![image](https://user-images.githubusercontent.com/67585977/86003085-94b01700-ba11-11ea-8a7f-67ec4f383f1a.png)

I get back 38 galleries.

![image](https://user-images.githubusercontent.com/67585977/86003120-a1cd0600-ba11-11ea-9978-0596821721dc.png)

If I add in "futanari" now,

![image](https://user-images.githubusercontent.com/67585977/86003173-b9a48a00-ba11-11ea-881d-d14821800b4f.png)

I get back *less* results. (Only galleries that contain all search terms)

![image](https://user-images.githubusercontent.com/67585977/86004598-d641c180-ba13-11ea-8966-78830a4eba24.png)

---

Finally, adding in another search term, with 'match all terms' *disabled*, doesn't refine the search any further.

![image](https://user-images.githubusercontent.com/67585977/86003524-32a3e180-ba12-11ea-9b52-271ca3287537.png)

I still get back the same results (Even though only 1 of those 14 contains "*electric shocks*":

![image](https://user-images.githubusercontent.com/67585977/86003558-42232a80-ba12-11ea-862f-c8856739eb45.png)

This means that all galleries that didn't match BOTH *"futanari"* and *anal* were excluded from the search, but not galleries that didn't contain *"electric shocks"*

---

My understanding would be that with 'match all terms' *disabled*, I would get back all galleries containing *any* of the search terms.

And with 'match all terms' *enabled*, I should get back *all* galleries containing *all* the search terms.

---

**Environment:**
 - OS: Windows 10
 - Firefox & Chrome (not browser related)
 - HPX Versions: ```Client 0.12.0```,  ```Server 0.12.4```, ```Database 0.8.0``` 
 - Database Dialect: SQLite & postgres (tested with both)

All the galleries were added by scanning a folder, and then using the nHentai plugin for adding metadata.

I'll gladly do some more testing and provide any detail necessary to help :)

(Do I need to do this with regex? I can do things like an 'or' case with regex, ("futanari"|"anal"), but I don't know any more.)

**Comment by twiddli** [comment]
Luckily, a better search is coming in the next version

**Comment by twiddli** [comment]
fixed in `v0.13.0`
