### ISSUE TITLE
[DatabaseError|300]: IntegrityError

### ISSUE THREAD

**Issue by GlassedSilver** [happypandax/happypandax#206]
**Describe the issue**
```
Server(300)
[DatabaseError|300]: IntegrityError((raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.IntegrityError) NOT NULL constraint failed: namespace_tags_userdata.user_id [SQL: INSERT INTO namespace_tags_userdata (_properties, last_updated, user_id, parent_id) VALUES (?, ?, ?, ?)] [parameters: ('{}', '2020-07-07 18:52:36.073870', None, 17)] (Background on this error at: http://sqlalche.me/e/gkpj))
```

**To Reproduce**
I'm simply loading the overview page of any of my stored doujinshi.

**Expected behavior**
no error

**Logs**
Will provide if needed. I would truncate URLs and filenames though.

**Screenshots**
n/a

**Environment:**
 - OS: Linux in a docker environment. Host OS is unRAID to be precise.
 - Firefox 78.0.1 (64-bit) on Windows 10 (1909 still, 2004 soon)
 - HPX Version latest as provided in the docker. (Client 0.12.0; Server 0.12.4; Database 0.8.0)

**Additional context**
n/a

**Comment by twiddli** [comment]
You're trying to mutate tags with a guest account? That's not supported.

**Comment by GlassedSilver** [comment]
I didn't notice that I at some point must have clicked on Guest login. No more error messages! Thank you so much!
