### ISSUE TITLE
Bookmarks/Saved for Later Button Not Working

### ISSUE THREAD

**Issue by nopenopenop** [happypandax/happypandax#213]
OS: Windows
Version: 0.13.2

The blue Bookmarks/Saved For Later button in the lower left that used to display a popup window no longer displays anything. For the brief period of time I got 0.13.1 working, it was also broken then as well. It was working fine for me in 0.12.4.

As a test, I created a fresh 0.13.2 install with no data at all and it behaved the same. No popup appears.

**Comment by twiddli** [comment]
fixed in `v0.13.3`
