### ISSUE TITLE
"Fatal error detected" When Trying to Run HPX_gui.exe

### ISSUE THREAD

**Issue by shikinoutaa** [happypandax/happypandax#214]
Operating System: Windows 10 v1909 x64
Version: 0.13.2

Hi there! Been playing around with the new updates, and I've had a trouble launching HappyPanda X from the GUI since the upgrade to 0.13.1.
When attempting to launch happypandax_gui.exe I'm met with the error pop-up:
**Fatal error detected
Failed to execute script gui**
![image](https://user-images.githubusercontent.com/36355885/91626833-6ce11f00-e980-11ea-98f3-1758d384e401.png)

On the other hand, when run directly from the command line, HappyPanda X launches and the web interface functions normally. I can't say that I've had this behavior when running v0.12.4 and older on the same hardware. 
![image](https://user-images.githubusercontent.com/36355885/91627131-250fc700-e983-11ea-9197-cce66f9af3b4.png)

So far in general troubleshooting, I've uninstalled and reinstalled HPX several times in places without elevated permission as well as the requisite reboots along side them but to no avail. In a little bit I will try reinstalling into a clean Windows 10 virtual machine in a little bit to see if it's just my specific OS installation or not.

**Comment by twiddli** [comment]
Hello can you try and start `happypandax_gui.exe` from the cmd to see if it'll print more info?
- Press Win + R
- Type `cmd` press enter
- with cmd open type `cd C:\path\to\hpx\folder`
- then run the gui with `./happypandax_gui.exe`

**Comment by shikinoutaa** [comment]
Thanks for getting back! I've tried running the hpx_gui executable from the command prompt (both with and without the leading syntax) but unfortunately it doesn't print more information, just runs the GUI exe without much more context as for why the script never runs.
![image](https://user-images.githubusercontent.com/36355885/91649888-88aef880-ea46-11ea-81b5-2c329c39df43.png)

I have since installed a fresh version of Windows 10 x64 v2004 on a VMWare Workstation Pro VM and it launches GUI just fine, which at least seems to indicate that something in HPX isn't playing well in my own main installation. 
![image](https://user-images.githubusercontent.com/36355885/91650121-8e5a0d80-ea49-11ea-89d0-efbcb66b93ef.png)
There could be a couple of reasons, specifically on the same machine I have an active installation of WAMP running modified imageboard code locally. I thought that maybe a port conflict or shared resources could be causing it. However, the same crash seems to happen whether or not WAMP and it's services are running or not. After a bit of quick research it seems as if the problem could lie somewhere with Python, as the "**Fatal error detected: Failed to execute script _____"** seems to be an error in Pyinstaller. Python and troubleshooting it are pretty far out of my wheelhouse, so that's just my own conjecture.

**Comment by twiddli** [comment]
Hello, I'll put out a build that prints more info soon.

**Comment by shikinoutaa** [comment]
Thanks twiddli! Please get i out at your convenience. 😊
In the meantime I'll try some other options. If I end up updating HPX or Windows I'll update this comment with more information later.

**Comment by zatsuna** [comment]
I also experienced this error on windows 7 x64, when I tried using vc_redist.x86.exe provided with HPX. After installing Microsoft Visual C++ 2015-2019 Redistributable (x86) I was able to boot HPX gui.

**Comment by shikinoutaa** [comment]
Heyy, thanks so much for the suggestion zatsuna! I grabbed the latest VC Redistributable, and sure enough happypandax_gui.exe boots without issue! Thank you so much for your time and suggestions guys, I couldn't have done it without you. 🥰 This issue is now closed.
