### ISSUE TITLE
Invisible Galleries after Upload

### ISSUE THREAD

**Issue by ZyonPlay** [happypandax/happypandax#216]
**Describe the issue**
After Uploading Galleries, they dissappear or not show up.
Happens in Version 0.13.x, 0.12.4 is fine.

The Inbox also says "Showing 1-0 of 9" and goes to "Showing 1-0 of 0" within 1 second.

**To Reproduce**
1. Go to 'Add -> Scan, add galleries link'
2. Click on Scan
3. Go to Inbox or All, nothing appears.

**Logs**
[error.log](https://github.com/happypandax/happypandax/files/5145499/error.log)
[esearch_stdout.log](https://github.com/happypandax/happypandax/files/5145500/esearch_stdout.log)
[plugin.log](https://github.com/happypandax/happypandax/files/5145501/plugin.log)
[redis_stdout.log](https://github.com/happypandax/happypandax/files/5145502/redis_stdout.log)
[activity.log](https://github.com/happypandax/happypandax/files/5145503/activity.log)

**Environment:**
 - OS: Windows 10
 - Chrome, also happens on HappyPandaX Client
 - Version 0.13.2

**Comment by twiddli** [comment]
Hello, this is related to #212
Please go to **About** -> Reindex Library (Choose one from the dropdown)

**Comment by twiddli** [comment]
`v0.13.3` should fix this, please reindex your library
