### ISSUE TITLE
Can't start HPX Win 10 due to ESearch error

### ISSUE THREAD

**Issue by mag2340** [happypandax/happypandax#224]
**Describe the issue**
Whenever I attempt to upgrade my HPX to 0.13.3 and start it, I get an ESearch server error

**To Reproduce**
1. Upgrade HPX from 0.12.4 to 0.13.3
2. Attempt to start the server

**Expected behavior**
Normal operation of HPX. I can't start it or use it without downgrading to 0.12.4.

**Logs**
**CMD:**
Running HPX version 0.13.3
Using sqlite database
Starting up, please wait...
'Failed to configure built-in ESearch server, process exit code: 1 also see logs\\esearch_stdout.log '
'Could not establish connection to ESearch server, aborting. '
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-Break to quit
Exception ignored in: <function Handle.Close at 0x033BC0C0>
Traceback (most recent call last):
  File "gevent\subprocess.py", line 261, in Close
TypeError: 'NoneType' object is not callable
Exception ignored in: <function Handle.Close at 0x033BC0C0>
Traceback (most recent call last):
  File "gevent\subprocess.py", line 261, in Close
TypeError: 'NoneType' object is not callable

**esearch_stdout.log (abridged, I'll attach the full file):**
2020-10-20T14:43:30,605][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [happypandax-testarossa_yami_momo] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[failed to bind service]; nested: IndexFormatTooNewException[Format version is not supported (resource BufferedChecksumIndexInput(SimpleFSIndexInput(path="E:\Porn\pic\happypandax\data\esearch\nodes\0\_state\segments_2i"))): 10 (needs to be between 7 and 9)];

**Environment:**
 - OS: Win 10 1809 x64
 - Browser and browser version: Ungoogled-Chromium 67.0.3396.87
 - HPX Version: 0.13.3

**Additional context**
Downgrading to 0.12.4 allows me to start HPX just fine. I also deleted the bin/win32/elasticsearch folder that you mentioned in the release for 0.13.2 and reinstalled the update. Fresh installs also work fine, it's just with my current database.
[esearch_stdout.log](https://github.com/happypandax/happypandax/files/5410927/esearch_stdout.log)

**Comment by twiddli** [comment]
Can you try deleting the `data/esearch` folder too? Don't worry, it's harmless.

**Comment by nayumiDEV** [comment]
> Can you try deleting the `data/esearch` folder too? Don't worry, it's harmless.

can't solve the problem
