### ISSUE TITLE
Unable to download nhentai galleries

### ISSUE THREAD

**Issue by jdevoldere** [happypandax/happypandax#236]
**Describe the issue**
"No matching download handler found for url https://nhentai.net/g/..." whenever I try to add an url for download.

**To Reproduce**
1. Clean install of HPX
2. Create an admin user
3. Start server
3. Open Webclient and login
4. Go to Downloads
5. Add a random nhentai gallery url
6. See error in log window (No matching download handler found for url https://nhentai.net/g/...)

**Expected behavior**
The hentai gallery to be downloaded without errors.

**Environment:**
 - OS: Windows 10
 - Browser and browser version: Firefox latest
 - HPX Version: v0.13.3

**Additional context**
Tested on two separate machines and same issue.

**Comment by jdevoldere** [comment]
Update: the same issue is also present with e-hentai galleries.

**Comment by 404Fox** [comment]
Make sure that the nhentai and ehentai downloader plugins are installed and enabled.
This is under a tab in the About page in the client.
