### ISSUE TITLE
Super Scary Update Statement

### ISSUE THREAD

**Issue by twiddli** [happypandax/happypandax#242]
![comeback](https://user-images.githubusercontent.com/11841002/111806521-5d043a80-88d2-11eb-89f7-6435c7611ba6.png)

I hope covid-19 is treating you well.
This is a much-needed update statement regarding the state of things I think.

### Preface
I want to start off by saying that everything about my hobby projects is for the learning experiences and having a platform to try out stuff freely. This means that because of no incentive to make loads of money or receive something big out of them many times I decide to make things hard for myself on purpose by rolling with my own solutions instead of proven ones that already exist. I've learned tons of stuff while developing HPX and also its predecessor HappyPanda, which I'm grateful for!
With that said, there was a time I hated JavaScript more than anything and wanted to avoid it at all costs, but that has since changed after discovering and learning Typescript. I now really like developing in JavaScript (Typescript).

### Next
I'll go straight to the points of things I want to do.
**The client is going to be rewritten.** I know what you may be thinking, cmon a rewrite!? Yes, really. To be honest the client is kinda trash. I used a really weird solution to make it and it has been a pain to develop in. Did you know that it took me more time to develop UI features than server stuff between releases? Was really painful. With the rewrite of the client, I am going to allow myself to make some very breaking changes to how the server and client communicate.
Anyway, I don't really wanna do double work so this will mean that all current development on the current web client will cease!

Next is, **the server will be rewr-**, just kidding. I'm not going to rewrite the server but I've learned a ton of stuff already, and there are some parts **I want to refactor** towards making it perform better.
I kinda miss writing C++ after working in Python and JS for so long, that's why I want to try and **write some parts of the server in C++** for the learning experience of mixing Python and C++.
I also want to focus largely on documentation and better info regarding things such as plugins and stuff. I hope I can get help on this.

Since I'm a busy uni student and also have some private projects I'm working on, time is going to be an issue. I will try my best to dedicate my time to this but sometimes it's going to be rough. Please bear with that.

### Going open source
Lastly, I'm planning to open source the application again. Yay!
I will start by open sourcing the development of the new client and after that, the server will follow suit once I've cleaned it up for it. I hope I can get some help with the development.

**Comment by twiddli** [comment]
I forgot to add

###  Transparency
I will try and be more transparent with the development process

-----------------------

Work on the client rewrite has begun here https://github.com/happypandax/happypandax/tree/dev/packages/client

**Comment by GlassedSilver** [comment]
Hey, just wanted to say I appreciate all that you've done already and that I'm looking forward to all further development of this application [set]. :)

**Comment by Hime-Dev** [comment]
I hope the server file will be published as soon as possible.

**Comment by Dystasia** [comment]
Great news!

**Comment by Zerendipity** [comment]
Waiting with baited breath the updates =D this is an amazing project.

**Comment by austinfttwxd** [comment]
is this still under development or has it been abandoned? having issues getting it to run from the unraid docker and it looks like the perfect utility for what I'm looking to do.

**Comment by austinfttwxd** [comment]
is this still under active development, I found it under the unraid app browser and it looks perfect for my use case, but I cant even get the webui up to start configuring it.
