### ISSUE TITLE
Fix permission problems on synology devices

### ISSUE THREAD

**Issue by uparrows** [happypandax/happypandax#243]
First of all ，i love this software . thanks to twiddli for developing this software ！
it works well on my ubuntu server , but when I try to install on another synology machine by docker , It fails to run due to an esearch error .
so I tried to figure it out , finally i found that's  caused by synology’s permission problem ，i've mount my comic folder to /content ,and my data folder to /data ,but in the container , hpx has no permission to access these folders .

i've built a dockerfile and a startup script to fix it .

dockerfile:

FROM ubuntu:20.04 as system
RUN useradd --create-home --no-log-init --shell /bin/bash happypandax
RUN apt update \
    && apt install -y tzdata locales
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone
ENV HPX_DOCKER=true
ENV HPX_CONTENT=/content
#ENV HPX_DATA=/data
WORKDIR /happypandax
ADD --chown=happypandax:happypandax happypandax0.13.3.linux.tar.gz /happypandax/
ADD --chown=happypandax:happypandax config.yaml /happypandax
ADD --chown=happypandax:happypandax startup.sh /
RUN mkdir $HPX_CONTENT && mkdir $HPX_DATA && mkdir /happypandax/data
RUN chmod -R 777 /happypandax && chmod -R 777 $HPX_CONTENT && chmod -R 777 $HPX_DATA && chmod -R 777 /happypandax/data
RUN chown -R happypandax:happypandax $HPX_CONTENT && chown -R happypandax:happypandax $HPX_DATA && chown -R happypandax:happypandax /happypandax/data
RUN chmod +x /startup.sh
EXPOSE 7007
EXPOSE 7008
ENTRYPOINT ["/startup.sh"]

startup.sh :

#!/bin/sh
chmod -R 777 /data /content /happypandax/data ;
chown -R happypandax.happypandax /data /content /happypandax/data ;
su - happypandax <<EOF
cd /;
exec ./happypandax/happypandax ;
EOF

config.yaml :

import:
    skip_existing_galleries: true
    transparent_nested_folders: true
server:
    disable_default_user: true
    require_auth: true
    allow_guests: false
watch:
    enable: true
    dirs:
      - ${HPX_CONTENT}
    options:
      ${HPX_CONTENT}:
        import.scan_on_startup: true
plugin:
    plugin_dir: ${HPX_DATA}

The principle is  user root  to change the user and permissions of the mounted folder to solve the problem of inaccessibility under Synology first  ,  then switch to the user happypandax  to solve the problem that esearch cannot run under the root user .

Hope it's helpful to users who also encounter this situation  .

i've also build a docker image to fix this problem ：https://hub.docker.com/r/dezhao/happypandax

**Comment by twiddli** [comment]
Hello, thank you for fixing this problem.
I will include this fix in the official docker image
