### ISSUE TITLE
Postgresql Errors

### ISSUE THREAD

**Issue by blastman0** [happypandax/happypandax#249]
**Describe the issue**
hello, can somebody explain to me how to setup postgresql server ? with sqlite it is very slow, and postgresql is faster, but gives me lots of errors like :

: happypanda.common.exceptions.CommandError: [CommandError|120]: Command(174) has failed with: [HappypandaError|100]: ProgrammingError((psycopg2.errors.SyntaxError) ERREUR: erreur de syntaxe sur ou près de « PRAGMA »
LINE 1: PRAGMA foreign_keys=1;
or
: sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) ERREUR: erreur de syntaxe sur ou près de « PRAGMA »
LINE 1: PRAGMA foreign_keys=1;
^

(Background on this error at: http://sqlalche.me/e/13/f405)

**To Reproduce**
1. Go to Client
2. Click on a book or go to browse
3. See error

**Expected behavior**

**Logs**
If applicable, include your ``error.log`` or ``debug.log`` found in ``[HPX]\logs\`` to help identifying your problem.

**Screenshots**

**Environment:**
 - OS: [Windows 10]
 - Browser and browser version [New Microsoft Edge]
 - HPX Version [0.13.3]

**Additional context**

**Comment by 404Fox** [comment]
Duplicate #232

**Comment by twiddli** [comment]
Follow the other issue
