### ISSUE TITLE
Status Update

### ISSUE THREAD

**Issue by Pewpews** [happypandax/happypandax#29]
<img src="https://user-images.githubusercontent.com/11841002/27642204-61ff0bc6-5c1e-11e7-8be9-f90586ced371.jpg" height="200">

Alright guys,
I want to release a preview version.
This preview version will have the following features:
> - View, read and basic gallery modification

> **Note**: It will not be possible to add or delete galleries in this version.

Accompained with this preview version is this single plugin:
> - A HP to HPX database converter.

For this release to be realized, the issues in [this](https://github.com/happypandax/server/projects/2) project needs to be done.
If i work fast, I believe those issues will be completed in about 2 weeks time at most.

That's all!

**Comment by Zuescho** [comment]
Glad to see the Project still growing.

**Comment by Tsubasaza** [comment]
Looking forward to it, thanks for the update.

**Comment by kimamb** [comment]
I'm also looking forward to it!
