### ISSUE TITLE
Possible compatibility with EHentai Downloader

### ISSUE THREAD

**Issue by rabaarabaa** [happypandax/happypandax#36]
https://github.com/ccloli/E-Hentai-Downloader

Everytime you download a gallery through here, inside the .zip there will be a txt with that gallery's metadata, since it'd be just to read a txt file it wouldnt be so hard I suppose (although this feature would be low priority)

**Comment by bluefiberbread** [comment]
That'd be a great feature, but  it'd also mean I'd have to re-download all of my stuff which I don't have time for =(

**Comment by Pewpews** [comment]
This has now been implemented in the [File Metadata plugin](https://github.com/happypandax/plugins/tree/master/plugins/File%20Metadata)
