### ISSUE TITLE
Separate User Profiles [Request]

### ISSUE THREAD

**Issue by TheJoe49** [happypandax/happypandax#4]
I thought it would be nice to have different profiles so if I wanted to allow my friend to use the server, but not mess with my database, he could. I was thinking something like separate tags, manga, and settings or have the choice to share those and just keep what you have read separate.

**Comment by Pewpews** [comment]
I wanted to update on this.
I'll implement separate settings, gallery read count and gallery last read.
I don't really know how separate tags would work..?
What is meant by separate manga? 

Your friend should be able to use his/her own client to connect to your server. He/She can read all your galleries with separate..- ah so you mean that they should be able to tag the galleries, but those tags are kept separate? The tags should be saved in your database, right?

**Comment by TheJoe49** [comment]
Separate manga would be something like he could upload comics on his profile without them showing up on mine

**Comment by rwchunk** [comment]
How about setting up filters? Ultimately everything will share the same library, but you can setup personal filters to hide things based on tags on those items. Dunno if this is implemented on a per-user basis yet, similar to the systems on ehentai/nhentai/tsumino.
![image](https://user-images.githubusercontent.com/19255865/68081098-59077380-fdd6-11e9-801f-cb56ce262f9f.png)

Additionally, you mentioned uploading - this would be a separate feature where a user can upload from their own device to the server.

**Comment by twiddli** [comment]
> but you can setup personal filters to hide things based on tags on those items

wow this is actually a really great idea

**Comment by twiddli** [comment]
Separate user profiles are continually being improved on. Filters are now per-user too, so I think this covers most things from here.
