### ISSUE TITLE
Tankobons, magazines, split chapters etc

### ISSUE THREAD

**Issue by bluefiberbread** [happypandax/happypandax#45]
How would Happypandax work around and display tankobons, magazines or galleries with split chapters into multiple .zip/.cbz files in the interface?

H:\Artists\Shunjou Shuusuke\[Shunjou Shuusuke] Ichizu na Toriko - A Earnest Captive [English] [SaHa]
https://puu.sh/z8Ljq/56208c8250.jpg

In this example, would it include 1.cbz, 2.cbz, 3.cbz, "everything else" and all of the images inside the folder "everything else" in the interface?

**Comment by Pewpews** [comment]
Hello, 1 chapter per `gallery` and then you group related galleries under a `Grouping`, or call it a `series namespace`. A tank then has its own object called a `Collection` in which you put individual galleries (chapters) into. A `Collection` can also be used for magazines. These are just the recommended usages of the few different kinds of objects. See [Recommended Usage](https://happypandax.github.io/server/api_general.html#recommended-usage) in the docs for more info.

**Comment by bluefiberbread** [comment]
Is there a way to make it an automated process? I have over hundred tankobons, magazines etc and it'd take ages to add the split chapters into different groups

**Comment by Pewpews** [comment]
I plan to implement various features that'll automate much of the gallery management. One such feature (and my most desired) is a way to split the different chapters that have been combined and put into a single archive or folder.

**Comment by bluefiberbread** [comment]
I've an idea, why not use the title of the filename and use multiple thumbnails and use an algorithm to choose the best hit?  Because then it would ignore filenames such as "Chapter #1" etc.

**Comment by Pewpews** [comment]
Unclear on what you're trying to say.
I suggest we wait till when I eventually implement gallery importing. It'll work mostly like the one from HP.

**Comment by Pewpews** [comment]
Searches for what? Where?

**Comment by twiddli** [comment]
The scanner supports some special syntax for more fine-grained control of the import process. See [Scanning for galleries](https://happypandax.github.io/faq.html#scanning-for-galleries) in the docs
