### ISSUE TITLE
Issue adding small galleries (<7 images)

### ISSUE THREAD

**Issue by thebrokenfacade** [happypandax/happypandax#50]
I have about 30 galleries in the .cbz format that the old happypanda refuses to add to the library. When added, all the archives are skipped with the reason "Empty Archive". I finally determined that they were being considered as empty archives because they have 7 or less images in them. 

- I tried renaming them using only alphanumeric characters and using a different directory on the disk. 
- I converted the images to a different file type just to be sure the images themselves weren't messed up
- They all have a file size between 1.7mb and 30mb, and I have galleries in that file size range that are properly detected, so I do not think it is a small file size causing the problem.
- Every single archive that is considered an empty archive has 7 or less images and a tags.txt file.

I hope in happypandax this issue can be resolved!

**Comment by Pewpews** [comment]
Hello, I suspect that it might be related to #1.
If you know how, then try running HP with changes in [this PR](https://github.com/Pewpews/happypanda/pull/184) to confirm this.

I'll put this issue on-hold until gallery addition is being implemented.

**Comment by twiddli** [comment]
Possibly fixed in `0.4.0`
