### ISSUE TITLE
Unable to start server/web-server on HPX 0.1.0

### ISSUE THREAD

**Issue by joshrharmon** [happypandax/happypandax#56]
**Describe the bug**
When attempting to run either happypandax or happypandax_gui and starting the server/web-server, the startup fails and exits. I've attached the output of the errors from start to finish in the "screenshots" section.

**To Reproduce**
1. Download and unzip the latest tar.gz for Linux (HPX 0.1.0)
2. Run happypandax from the command line
3. See output displaying many errors

**Expected behavior**
The server and web-server should start normally.

**Screenshots**
[Error log](https://pastebin.com/VNDnRBEy)

**Environment:**
 - OS: Xubuntu Linux 18.04, Kernel 4.15.0-23-generic (edited for incorrect Xubuntu ver)
 - Firefox Quantum 60.0.2
 - HPX ver. 0.1.0

**Additional context**
I've tried to start the program both through the command line and the GUI, both result in the same errors.

**Comment by Pewpews** [comment]
Hi, thanks for reporting. I'm also able to reproduce it on the Linux Subsystem for Windows. I'll work on a fix.

**Comment by joshrharmon** [comment]
Thanks so much, looking forward to it!
