### ISSUE TITLE
Ability to scan nested folders

### ISSUE THREAD

**Issue by joshrharmon** [happypandax/happypandax#57]
**Is your feature request related to a problem? Please describe.**
I cannot scan in my collection because they are organized into nested folders. Unfortunately, as of now, HPX can only scan directories where the content is directly in the folder.

**Describe the solution you'd like**
The ability to scan in content within nested folders recursively.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Pewpews** [comment]
A workaround is to add the galleries in HappyPanda and then import them into HPX through HPtoHPX. Use the `--offset` arg to only import the newly added galleries.

**Comment by twiddli** [comment]
implemented in `0.4.0`
