### ISSUE TITLE
UNIQUE constraint failed: language.name

### ISSUE THREAD

**Issue by Yukariin** [happypandax/happypandax#58]
**Describe the bug**
Exception on adding any gallery

**To Reproduce**
1. Start happypandax
2. Go to localhost:7008
3. Login
4. Go to 'Manage'
5. Set the path
6. Press 'Submit'
7. Look into logs/console

**Expected behavior**
Gallery successfully added

**Logs**
[error.log](https://github.com/happypandax/happypandax/files/2238661/error.log)

**Environment:**
 - OS: Linux
 - Browser and browser version: chrome 67
 - HPX Version: 0.2.0

**Additional context**
Looks like it tries to create new language called 'English' which already exists.

**Comment by Pewpews** [comment]
Hello, I worked a lot on the database for `v0.2.0` and might have fixed this. Please try and see if the issue still persists.
