### ISSUE TITLE
Add way to update data and pages of galleries in database

### ISSUE THREAD

**Issue by emmauss** [happypandax/happypandax#59]
**Is your feature request related to a problem? Please describe.**
I have got some partially downloaded galleries. though their downloads are pending in my downloader, and can be finished if given the time. I do regular updates on the hpx db. and now with the fact that hpx will only add new galleries, and not ones that may have been modified. so those galleries are left incomplete in the db.

**Describe the solution you'd like**
A way of requesting a galleries update, either manually or automatically

**Comment by twiddli** [comment]
implemented in `v0.9.0`
