### ISSUE TITLE
What file formats does happypandax support?

### ISSUE THREAD

**Issue by Ozzon60** [happypandax/happypandax#61]
I feel like I'm missing a page of all the information I need...

**Comment by Pewpews** [comment]
Hello
HPX supports folders with loose files and
```
    ZIP = '.zip'
    RAR = '.rar'
    CBR = '.cbr'
    CBZ = '.cbz'
    TARGZ = '.tar.gz'
    TARBZ2 = '.tar.bz2'
    TARXZ = '.tar.xz'

    JPG = '.jpg'
    JPEG = '.jpeg'
    BMP = '.bmp'
    PNG = '.png'
    GIF = '.gif'
```
Feel free to add these into the docs if you wish to contribute.

**Comment by Ozzon60** [comment]
@Pewpews Do you think pdf will be added? Know any good pdf to any of those format converter?

**Comment by Pewpews** [comment]
PDF? That's a very peculiar format to store galleries in. I don't know of any good offline tool. Maybe try https://github.com/limingjie/pdf_to_image.
I don't think this format will be added unless there's a huge demand.

**Comment by Ozzon60** [comment]
@Pewpews Appreciate it, and how to I add labels so you don't have too xD?

**Comment by Pewpews** [comment]
Github labels? Only contributors and the repo owner can assign them.

>How do I add a bunch of manga? I tried the scan feature but I can't get it to work.

It depends on how your files are organized. Try to describe how your files are organized. If your galleries are nested in subfolders HPX won't detect them, see #57. It's coming in `0.4.0`.
