### ISSUE TITLE
tags and edit not working?

### ISSUE THREAD

**Issue by ve3lst** [happypandax/happypandax#63]
**Describe the bug**
not sure if it is not working or it's still a wip, but when i go to a gallery and press edit on the top right it do nothing.
and i tried to add happypanda db in the server log it says it did import successfully

`
>: Creating gallery lists
>: Adding 1 languages...
>: Adding 4 artists...
>: Adding 1 gallery types...
>: Adding 25 gallery tags...
>: Adding 10 galleries...
>: Adding 0 gallery lists...
`

 but when i go to the gallery in the web client i don't see the tags in the gallery itself, but when i go to directory tags i see all the tags, but its not linked with the gallery

**Environment:**
 - OS: windows 7
 - Browsers firefox and chrome
 - HPX Version 0.2.0

**Comment by Pewpews** [comment]
Hello, gallery editing is coming next version.
As for your second issue, are you trying to edit a gallery in HappyPanda that has already been imported? These changes to the gallery in HP will not be reflected on the gallery in HPX.

**Comment by ve3lst** [comment]
oh cool, good luck then. 
about the import thing, i've tags already set in HP and i imported the db to HPX (with the tags),
this gallery for example:
it shows that it have to tags at all:
![001](https://user-images.githubusercontent.com/18611574/44347742-4c348380-a4a1-11e8-9490-e49bbea4ec67.PNG)
and this it the tags pages (all imported from HP db):
![002](https://user-images.githubusercontent.com/18611574/44347784-6cfcd900-a4a1-11e8-8264-ee392ee972e6.PNG)
here what i see when i click on any tags (tried all, inbox and Library, this gallery in inbox tho) 
![003](https://user-images.githubusercontent.com/18611574/44347813-80a83f80-a4a1-11e8-8e60-f75f2c3a4054.PNG)

**Comment by Pewpews** [comment]
Hello, tell me if the issue still persists in the latest version.

**Comment by ve3lst** [comment]
i cant start the server after i updated (i installed the 0.3.0 in the same folder as 0.2.0. this is how the 
update is done, right?) 

i get this output in the gui
`
>: Using sqlite database
>: Checking for database update
>: Database update found. Updating...
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('user_id', 'user', 'id')' could not be located in PRAGMA foreign_keys for table artist
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('language_id', 'language', 'id')' could not be located in PRAGMA foreign_keys for table artistname
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('alias_for_id', 'artistname', 'id')' could not be located in PRAGMA foreign_keys for table artistname
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('user_id', 'user', 'id')' could not be located in PRAGMA foreign_keys for table category
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('user_id', 'user', 'id')' could not be located in PRAGMA foreign_keys for table circle
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('category_id', 'category', 'id')' could not be located in PRAGMA foreign_keys for table collection
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('user_id', 'user', 'id')' could not be located in PRAGMA foreign_keys for table collection
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('user_id', 'user', 'id')' could not be located in PRAGMA foreign_keys for table event
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('user_id', 'user', 'id')' could not be located in PRAGMA foreign_keys for table filter
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('language_id', 'language', 'id')' could not be located in PRAGMA foreign_keys for table gallery
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('grouping_id', 'grouping', 'id')' could not be located in PRAGMA foreign_keys for table gallery
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('taggable_id', 'taggable', 'id')' could not be located in PRAGMA foreign_keys for table gallery
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('category_id', 'category', 'id')' could not be located in PRAGMA foreign_keys for table gallery
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('status_id', 'status', 'id')' could not be located in PRAGMA foreign_keys for table grouping
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('user_id', 'user', 'id')' could not be located in PRAGMA foreign_keys for table language
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('user_id', 'user', 'id')' could not be located in PRAGMA foreign_keys for table metalist
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('alias_for_id', 'namespace', 'id')' could not be located in PRAGMA foreign_keys for table namespace
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('language_id', 'language', 'id')' could not be located in PRAGMA foreign_keys for table namespace
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('alias_for_id', 'namespace_tags', 'id')' could not be located in PRAGMA foreign_keys for table namespace_tags
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('tag_id', 'tag', 'id')' could not be located in PRAGMA foreign_keys for table namespace_tags
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('language_id', 'language', 'id')' could not be located in PRAGMA foreign_keys for table namespace_tags
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('user_id', 'user', 'id')' could not be located in PRAGMA foreign_keys for table namespace_tags
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('parent_id', 'namespace_tags', 'id')' could not be located in PRAGMA foreign_keys for table namespace_tags
>: D:\Program Files\hpx\sqlalchemy\dialects\sqlite\base.py:1425: SAWarning: WARNING: SQL-parsed foreign key constraint '('namespace_id', 'namespace', 'id')' could not be located in PRAGMA foreign_keys for table namespace_tags
>: An error occured in the database initialization process: index ix_page_number already exists

`

**Comment by twiddli** [comment]
tags have been improved since then, please reopen if issue still occurs
