### ISSUE TITLE
Viewing galleries with same tag not working properly

### ISSUE THREAD

**Issue by observeroftime02** [happypandax/happypandax#64]
**Describe the bug**
When clicking on tags in galleries, and selecting "show galleries" the search term is not inserted correctly, and the tagged galleries don't show up correctly.

**To Reproduce**
1. Import galleries downloaded with Hdoujin downloader, with metadata being saved in info.txt, namespaces and tag properties on
2. Go to imported gallery, looks like this 
![image](https://user-images.githubusercontent.com/43228249/45476605-31e27400-b6f4-11e8-9eea-6a1f3bb46a81.png)

(the URL for the search is /library?search=%22Female%22%3A%22ponytail%22)

3. Click on a tag, select show galleries 
![image](https://user-images.githubusercontent.com/43228249/45476676-69512080-b6f4-11e8-81b5-8d8144f8feec.png)
4. You're taken to this search, which displays incorrect results 
![image](https://user-images.githubusercontent.com/43228249/45476738-9e5d7300-b6f4-11e8-8143-1dffb274b7ae.png) 

**Expected behavior**
I expect only galleries with the Female:ponytail tag to show up. If the search was inserted as "Female:ponytail" instead of "Female":"ponytail" the correct results would be displayed.

Furthermore, searching for "Female":"ponytail" from the main gallery page in a new search **will** display the correct galleries (URL is library?page=1&search=%22Female%22%3A%22ponytail%22). Notice there's a page selector present in the URL here, whereas the "show galleries" search from a tag doesn't have that present.

It only seems to be an issue when going through the "show tagged galleries" function. Either way there are some really inconsistent behaviours when using the same search term manually entered vs. showing tagged galleries via clicking on a tag. 

Edit: I've messed around with it some more, it seems like even just entering a space and deleting and then hitting enter in the search bar after the search term gets inserted after clicking on "show galleries" from a tag seems to produce the desired results. I'm losing it. 

By making the space and delete modification in the search box after the term gets inserted from the show galleries function, the URL changes from
http://xxx:7008/library?search=%22Female%22%3A%22ponytail%22
to 
http://xxx:7008/library?page=1&search=%22Female%22%3A%22ponytail%22
which yields desired results.

**Environment:**
- Windows 10
- Chrome

**Additional context**

**Comment by twiddli** [comment]
Hello, thanks for reporting. This is an inconsistent behaviour that needs to be fixed.

**Comment by twiddli** [comment]
fixed in `0.4.0`
