### ISSUE TITLE
Inconsistent WebUI across mobile devices

### ISSUE THREAD

**Issue by observeroftime02** [happypandax/happypandax#65]
**Is your feature request related to a problem? Please describe.**
The WebUI looks good on desktop, but accessing it on mobile devices is very frustrating due to the search box being either completely obscured or so small that it becomes practically unusable

Here are four screenshots taken from my devices.

**Galaxy Tab S2 portrait mode**
![screenshot_20180913-162806](https://user-images.githubusercontent.com/43228249/45521497-0a7ebc00-b773-11e8-9c4b-509a1366f4e3.jpg)

**Galaxy Tab S2 landscape mode**
![screenshot_20180913-162842](https://user-images.githubusercontent.com/43228249/45521500-0d79ac80-b773-11e8-96c1-3263022dc360.jpg)

**Galaxy Note 8 portrait mode**
![screenshot_20180913-163044_chrome](https://user-images.githubusercontent.com/43228249/45521507-179bab00-b773-11e8-8a23-61bae98b2767.jpg)

**Galaxy Note 8 landscape mode**
![screenshot_20180913-163347_chrome](https://user-images.githubusercontent.com/43228249/45521510-19fe0500-b773-11e8-9c54-da7e8bf6683e.jpg)

The only proper layout that leaves the search box accessible and usable is the Note 8 in portrait mode.

**Describe the solution you'd like**
Move the search box below the All | Collection | Gallery buttons, and have the Filter and Sort selection menus below the search bar when a mobile user agent is detected. Basically the way it looks on the Note 8 in Portrait mode.

**Describe alternatives you've considered**
Simply not using the search function with mobile devices for the time being.

**Comment by twiddli** [comment]
Fixed in `v0.6.0`
