### ISSUE TITLE
[Question] How would this be solved in Happypandax?

### ISSUE THREAD

**Issue by bluefiberbread** [happypandax/happypandax#66]
I don't know how to explain this properly, but is there a solution for this now? I tend to download tankobons, create a folder for the tankobon and  split the chapters into several zip files. Will Happypandax be able to find tags etc for this type of hierarchy in my directories?

https://i.imgur.com/vUzqLlq.jpg

**Comment by twiddli** [comment]
Hello, you can import the chapters as single galleries and then group them together in a collection or a grouping. You can fetch tags for the chapters as they are treated as standard galleries in HPX. But note that neither of these things have been implemented yet. Metadata fetching is coming next version.

**Comment by bluefiberbread** [comment]
Awesome, is there a way to automatically group split chapters into a tank or will I have to do it manually

**Comment by twiddli** [comment]
In `0.4.0` it is now possible to [automatically group them](https://happypandax.github.io/faq.html#scanning-for-galleries) on import.
