### ISSUE TITLE
Scanning a large directory causes mangas to be missed

### ISSUE THREAD

**Issue by waz1500** [happypandax/happypandax#68]
**Describe the bug**
Hi, 
I'm trying to add my existing manga collection for use with HPX. I have currently 6378 folders nested in one main folder called "Manga". I am using the File Metadata plugin currently enabled to read my hdoujindownloader generated info.txt files for the metadata. Upon scan, only 6119 folders are found resulting in a missing 259 folders not being added. Every manga folder does contain it's own info.txt file and titles do not exceed the windows character limit of 255 for folder naming. I have checked the log file and the error 
"**--ERROR  [database].happypanda.core.db: NO GROUPING NAME 4"** is repeated about 5000 times resulting in a large error.log file which may or may not have something to do with the missing galleries. I couldn't find this error in any of the previous issues that are solved.  

I've tried to use the add only new galleries detected option in HPX but no new galleries are detected after another scan.  

I've also attempted to add the entire gallery in HappyPanda and then import them into HPX through HPtoHPX however whilst in Happypanda, it does state 6378 folders are imported, only 800 or so are seen and on a lot of galleries I get "gallery does not exist". 
Upon trying to import the new database to HPX I get:
**"Database update found. Updating...
An error occured in the database initialization process: index ix_artist_user_id already exists**" and the server automatically shuts down. 

Am I trying to add too much at once perhaps?

**Environment:**
Windows 10
Chrome Version 69.0.3497.100 (Official Build) (64-bit)
HappyPanda X v0.3.0

**Comment by emmauss** [comment]
try this. delete( or move) your current HPX database. start HPX once, to create a blank db, then do an convert with your old HP db.

**Comment by twiddli** [comment]
Hi, I have in addition to #57, also fixed an issue where only folders with all files being images were recognized as being galleries. I think HP also has this issue, I don't remember. You can try it  out in `0.4.0`.

**Comment by waz1500** [comment]
Just wanted to give an update on this issue now that HappyPanda X v0.5.2 is out along with the updated File Metadata plugin 0.3.0b. 

For the most part, the errors I had in my initial post are largely gone. The missing 259 folders not being added I believe are those with chapters. 
An example layout for these nested folders is outlined below. In this case it's multiple works in the same collection. 
```
G:/Manga
      [Kousaka Jun] Pm Gals
                 PM GALS Sun Moon Mao  PM GALS SUNMOON MALLOW
                 PM GALS Ash Unrivaled  PM GALS サトシ無双
                 PM GALS Compilation  PMGALS総集編
                 PM GALS Iris no Turn!!  PM GALS アイリスのターン!!
                 PM GALS XY
                 PM GALS XY 2
                 PM Gals!
      info.txt 
```
The metadata file in the above exmaple:
[info.txt](https://github.com/happypandax/happypandax/files/2557748/info.txt)

Although checking "treat nested folders as being transparent" upon directory scan helps it can result in a messy collection with chapters being treated as a standalone gallery. 

I have been attempting to utilise the regex functions in the "Scanning for galleries" section of the faq. 

Using `root/{collection}/{gallery}` I can at least mass group these folders into the correct collection name in this case "Pm Gals". Although it seems HPX is grabbing the the full folder name in this case "[Kousaka Jun] Pm Gals" as the collection name. 

My question is if there is a regex command I could use upon initial scan to exclude anything within the [ ] in my folder name and just have whatever comes after that in this case "Pm Gals"?

Also, would it be possible for the info.txt file to apply to all the sub folders (galleries) within the main series folder?
At the moment, it looks like the metadata within the info.txt file only apply's to the top folder in this case "PM GALS Sun Moon Mao  PM GALS SUNMOON MALLOW" whereas I would like all the metadata to apply to all those folders as there is nothing in the above info.txt file that is specific to that one gallery. 
I have attached the image for better visual clarification. 
As you can see only one of those scanned galleries have the green metadata file icon.
![hpx metadata](https://user-images.githubusercontent.com/17833884/48141599-200bf000-e2a3-11e8-831e-8dc0043d4d81.png)

Perhaps it could be possible to utilise the `CHAPTERS` data from the info.txt file. It dictates that there are in my case 7 chapters which corresponds to the 7 sub-folders within the main folder. 

I think my issue may also be linked in with issue along with twiddli's comment about combining these separate chapters into one single archive.
https://github.com/happypandax/happypandax/issues/45

Thank you twiddli for these updates :)
