### ISSUE TITLE
Sorting by Random

### ISSUE THREAD

**Issue by LeadingChip** [happypandax/happypandax#73]
**Describe the bug**
Switching pages when it's ordered by random will shuffle everything everytime you switch page, so you may find duplicates going on with the pages, and you can't go on precedent pages because it'll shuffle again.

**To Reproduce**
1. Sort by random

**Expected behavior**
I think every page should be randomized once

**Environment:**
 - HPX Version: 0.5.2

**Comment by twiddli** [comment]
Hi thanks for the report, this is not really a bug but an implementation detail. The code and time required to fix this outweighs the benefits.
