### ISSUE TITLE
Remembering Read Progress and Updating Read Count only after Reaching Last Page

### ISSUE THREAD

**Issue by SophtwhereDev** [happypandax/happypandax#76]
Not sure if this is a common request but having HPX remember the page I was on when I last stop reading something and allowing me to pick up where I left off is essential to me. It would be an added bonus to pair this feature with the read count only updating when you read something from beginning to end or somewhere in the middle to the end.

I'm not sure whether you have a preference on how to implement this on the user interface but I was thinking something along the lines of the read button being split into 2 where one will allow you to start reading from the beginning and the other allowing you to continue from where you left off, if it's something you've partially read.

Additionally, in the case where continue is an available option and the user chooses to read from the start, then an option popping up to either over-write read progress or keep old read progress when the user tries to leave the reader would be convenient.

**Comment by twiddli** [comment]
implemented in `v0.9.0`
