### ISSUE TITLE
Regex galleries naming

### ISSUE THREAD

**Issue by waz1500** [happypandax/happypandax#77]
I'm having a little trouble with nested folders using the new regex commands in HPX v0.5.2 . 

An example layout for these nested folders is outlined below. In this case it's multiple works in the same collection. 
```
G:/Manga
      [Kousaka Jun] Pm Gals
                 PM GALS Sun Moon Mao  PM GALS SUNMOON MALLOW
                 PM GALS Ash Unrivaled  PM GALS サトシ無双
                 PM GALS Compilation  PMGALS総集編
                 PM GALS Iris no Turn!!  PM GALS アイリスのターン!!
                 PM GALS XY
                 PM GALS XY 2
                 PM Gals!
      info.txt 
```
The metadata file in the above exmaple:
[info.txt](https://github.com/happypandax/happypandax/files/2557748/info.txt)

Although checking "treat nested folders as being transparent" upon directory scan helps it can result in a messy collection with chapters being treated as a standalone gallery. 

Using `root/{collection}/{gallery}` I can at least mass group these folders into the correct collection name in this case "Pm Gals". Although it seems HPX is grabbing the the full folder name in this case "[Kousaka Jun] Pm Gals" as the collection name and auto populating the series entry with the folder name of the gallery.  

My question is if there is a regex command I could use so that HPX can exclude anything within the [ ] in my folder name when it populates the ```Collection:```  field and just have whatever comes after that in this case "Pm Gals"?

**Comment by twiddli** [comment]
Hi, that sounds like a completely separate feature. The scanner only uses the patterns to check whether a folder/file should be included in the results or not.
Being able to mass-edit multiple collections and galleries by regex is something I was planning to add in the the future. With that implemented, something like this would be possible.
The only way right now would be with a plugin.

**Comment by waz1500** [comment]
Ah thanks for the update twiddli. If regex was implemented on that scale I probably would use something like `(?<=\[)(.*?)(?=\])`
I look forward to that feature for sure.
