### ISSUE TITLE
Enable metadata to apply to subfolders within a main series folder

### ISSUE THREAD

**Issue by waz1500** [happypandax/happypandax#78]
Would it be possible for the info.txt generated by hdoujin to apply to all the sub folders (galleries) within the main series folder?

An example directory structure illustrating the problem:
```
G:/Manga
      [Kousaka Jun] Pm Gals
                 PM GALS Sun Moon Mao  PM GALS SUNMOON MALLOW
                 PM GALS Ash Unrivaled  PM GALS サトシ無双
                 PM GALS Compilation  PMGALS総集編
                 PM GALS Iris no Turn!!  PM GALS アイリスのターン!!
                 PM GALS XY
                 PM GALS XY 2
                 PM Gals!
      info.txt 
```
The metadata file in the above example:
[info.txt](https://github.com/happypandax/happypandax/files/2557748/info.txt)

At the moment, it looks like the metadata within the info.txt file only apply's to the top folder in this case "PM GALS Sun Moon Mao  PM GALS SUNMOON MALLOW" whereas I would like all the metadata to apply to all those folders as there is nothing in the above info.txt file that is specific to that one gallery. 
I have attached the image for better visual clarification. 
As you can see only one of those scanned galleries have the green metadata file icon.
![hpx metadata](https://user-images.githubusercontent.com/17833884/48141599-200bf000-e2a3-11e8-831e-8dc0043d4d81.png)

Perhaps it could be possible to utilise the `CHAPTERS` data from the info.txt file. It dictates that there are in my case 7 chapters which corresponds to the 7 sub-folders within the main folder.

Currently using HappyPanda X v0.5.2 with the updated File Metadata plugin 0.3.0b enabled.

**Comment by twiddli** [comment]
Hi, I foresee that this could easily cause unexpected and unwanted results. For instance, in this case, the title `PM GALS サンムーン` and the URL `http://www.tsumino.com/Book/Info/31233/pm-gals-sunmoon-pm-gals-` would be applied to all those galleries in that folder, which I'm guessing is not something you'd want. For this to work, there would be a lot of edge cases to account for, adding more complexity to the whole thing.

**Comment by twiddli** [comment]
The way I would solve this would be by stripping the `info.txt` file down to the bare minimum of common data, then copy it to every gallery in the folder.
If there's a lot of collections like this, I'd make a small simple script to do the job.
