### ISSUE TITLE
Include and exclude in metadata search

### ISSUE THREAD

**Issue by joejoejoe3652** [happypandax/happypandax#79]
Hey, I love the work you are doing, and just wanted to bring back a long forgotten suggestion from years ago back in the original HappyPanda. I, and others would love to have this implemented for easier tagging!

"It would be great if in future iterations, you can include or exclude keywords while automatically searching for tags. For example, currently for automatic metadata tagging, it would chose the first source, but that is usually the Japanese original one while the English title would be further up on the list. Instead of choosing the first source, could you implement a feature where it selects the source with the keyword "english" instead and if there is no english source, then tag using the first source it finds or a secondary tag, like Japanese. This would make auto tagging a lot more accurate.

I love what you are doing and thanks for making this program!"

**Comment by twiddli** [comment]
Hi, see `preferred_language`, one of the available options by the [ehentai metadata plugin](https://github.com/happypandax/plugins/tree/master/plugins/EHentai%20Metadata)
