### ISSUE TITLE
Query for metadata does not work on some galleries

### ISSUE THREAD

**Issue by joejoejoe3652** [happypandax/happypandax#81]
**Describe the bug**
Query metadata for certain galleries just doesnt work. I have the plug ins installed and logged into both e and exhentai. Screenshot of the gallery in question

https://ibb.co/mytZ4zG

zip file in question, tested in 7zip, the file is fine
https://ufile.io/rcw95

Exhentai link:
https://exhentai.org/g/27584/ce17011e1e/

This is not the only gallery that does not respond to query. Most of my galleries are fine, but some does the same thing. I have replace old metadata enabled, still does not do anything.

**To Reproduce**
1. Scan folder with file
2. Query for metadata
3. Nothing changed. 

**Expected behavior**
Metadata should be found and applied.

**Logs**

https://ufile.io/eypxl

**Environment:**
 - OS: Win10
 - Browser and browser version Firefox 63.0
 - HPX Version 0.6.1

**Comment by twiddli** [comment]
Hi, the plugin uses a gallery's file or folder name when looking it up if you have the option `filename_search` set to true. Did you account for this?

**Comment by joejoejoe3652** [comment]
Yea, I havent changed the default for that in the config file, so I think its set to true. 

![2](https://user-images.githubusercontent.com/20387677/49096310-513f6680-f238-11e8-8c17-27cf7204fcb3.PNG)

**Comment by twiddli** [comment]
I get no results when i search with `(C68) [RIROLAND (Kuuya, Satomi Hiroyuki)] MOJER (Major) [English]` (the name of the gallery file), which is the name being used when `filename_search` is set to true.

**Comment by joejoejoe3652** [comment]
Oh ok, i see. Thanks for the help! The query was able to find it when filename search was set to false. Thanks for the help!
