### ISSUE TITLE
Gallery scan becomes slower with larger database

### ISSUE THREAD

**Issue by emmauss** [happypandax/happypandax#89]
**Describe the bug**
Gallery scans become much slower when the database is very large.

**To Reproduce**
1. Create a new setup, and import a relatively small amount of galleries from a folder, (~1000 galleries)
2. Do a gallery scan on the same folder. Note the rate when it starts comparing galleries.
3. Repeat for another setup with a much larger database. Note the rate.

**Expected behavior**
The rate should be more or less equal.
**Environment:**
 - OS: Windows 10
 - Firefox 64.0.2
 - HPX Version [e.g. 22]

**Additional context**
All scans were done on an external HDD, so impact from other apps due to disk usage was minimal. Database used was postgres

**Comment by twiddli** [comment]
should be fixed/improved in `v0.9.0`
