### ISSUE TITLE
Unable to add 'Series' to item if another item has same 'Series' already applied.

### ISSUE THREAD

**Issue by crimsonraes** [happypandax/happypandax#90]
**Describe the bug**
Whenever a gallery's 'Series' tag is changed to one that is already used by another gallery, HPX throws '[100] HappypandaError: An unhandled critical error has occurred: IntegrityError' and leaves the 'Series' tag unchanged.

**To Reproduce**
1. Have at least 2 galleries.
2. Set gallery 1's 'Series' tag to 'xyz'.
3. Set gallery 2's 'Series' tag to 'xyz' (Or whatever was given to gallery 1. As long as it's the exact same spelling.)
4. See error.

**Expected behavior**
Both galleries' 'Series' tag should be set to the same series.

**Logs**
[error.log pastebin](https://pastebin.com/zR9durTB)

**Environment:**
 - OS: W10
 - Browser and browser version: chrome 71.0.3578.98 
 - HPX Version: client:0.7.0, server:0.7.0, database:0.4.0

**Additional context**

**Comment by twiddli** [comment]
fixed in `v0.8.0`
