### ISSUE TITLE
Galleries showing wrong (and too many) Circles

### ISSUE THREAD

**Issue by ub333** [happypandax/happypandax#91]
**Describe the bug**
I noticed an issue where galleries sometimes show a bunch of Circles that shouldn't be there:
![image](https://user-images.githubusercontent.com/46982788/51649691-684dbc80-1f3a-11e9-9e7f-8d3a82ef1401.png)

In this case, the Gallery should really only be showing one circle.

**To Reproduce**
I've been trying out HPX for organizing HCG galleries. One thing about eroges is that they often have several artists. I poked into the database and I think the problem here is that Circles don't seem to be associated to specific galleries, just to artists. So when a gallery is queried, it can only know all the artists associated with it, and then it goes and gets every circle those artists are associated with!

This also works the other way (or I should say doesn't work) - when I query on a circle, it returns a bunch of incorrect results, probably because some artists have contributed to multiple circles. 

![image](https://user-images.githubusercontent.com/46982788/51650152-ffffda80-1f3b-11e9-88b0-2d647c73c009.png)

**Expected behavior**
Galleries should display the correct Circle(s)
Searching on Circle should return correct results

**Logs**
n/a

**Environment:**
 - OS: MacOS 10.14.2
 - Chrome 71.0.3578.98
 - HPX Version 0.7.0
- DB Version 0.4.0; using Postgres

**Additional context**
Eroges really go by Circle, and HPX isn't quite there yet - I'd also like to be able to sort by Circle, and be able to show Circle on the galleries list, not just Title/Artist (as in second screenshot)

**Comment by ub333** [comment]
> Hi, this is interesting because when designing the db, I intentionally went with circle by artist to simplify things. So this really is the intended result.
> Would you not consider cases like these where the circle is not associated with all of an artist's work to be edge cases?

While what I posted is the most extreme example that I've seen of the issue, I don't feel it's an edge case. I'd been seeing some weirdness with how HPX handles circles and it just wasn't until this that I suspected what might be happening. Many artists who contribute to eroges also have a different circle that they release h-dougins under. Unless wanting to organize a large amount of HCG galleries using HPX is itself an edge case, in which case - you're the developer, so fair enough. 🙂

**Comment by ub333** [comment]
Did a few queries to get some numbers.

My database has 508 galleries, 422 artists, and 196 circles.
I created a new database just for HCG galleries.
Of those, 141 artists are associated with >1 circle (with some associated with as many as 5 circles).
Going the other way, 104 circles have >1 artist associated with them, with the worst having 42 (!!) artists associated with them.

I have another database with 656 galleries of only h-doujins and it only has 15 artists associated with >1 circle, so you're right in that this mostly will only happen with HCG galleries.

**Comment by twiddli** [comment]
It is now possible to attach circles to galleries alone in `v0.10.0`
