### ISSUE TITLE
Setup HPX

### ISSUE THREAD

**Issue by simonrule** [happypandax/happypandax#92]
PLease can anyone make video on how to setup HPX

**Comment by twiddli** [comment]
Hi, can you specify a little bit more about what you're having trouble with?
Is the guide written here not sufficient? https://happypandax.github.io/usage.html#setting-up
If not, can you tell me why? Maybe it's too technical?

**Comment by simonrule** [comment]
well i downloaded the program i leave everything as default i didnt change anything on the configuration
http://prntscr.com/mdzhsu
when click open web client i get this
http://prntscr.com/mdzihg

**Comment by twiddli** [comment]
Just click on *Start server*

**Comment by twiddli** [comment]
The webclient is served at `localhost:7008` with the default settings

**Comment by elagi** [comment]
I have the same issue as in http://prntscr.com/me1my8 even after setting ports to 7008.

**Comment by twiddli** [comment]
>even after setting ports to 7008.

You mean you set both ports to 7008? 
The webclient and server shouldn't be using the same port or it won't work.

**Comment by elagi** [comment]
I'm sorry I've copied the wrong link. Here's mine anyway: https://imgur.com/a/s0FcIHl

**Comment by twiddli** [comment]
try `server.host_web`  setting to `localhost`

**Comment by elagi** [comment]
It worked, thanks.
