### ISSUE TITLE
Scanner Not a RAR/ZIP file

### ISSUE THREAD

**Issue by calgara12** [happypandax/happypandax#93]
When i try to scan my library the scan always gets interrupted. The logs say either badzipfile: File is nota zip file, or badrarfile: Not a rar file.

Although the files are working fine when i try to open/read them with other programs.

**Comment by twiddli** [comment]
Hi, the files have most likely been given the wrong extension. In the programs that can read them, can you see if they provide a way to check the real file type and check if they differ?
The scanner will be improved in the next update to be more resilient towards errors and not halt.

**Comment by calgara12** [comment]
the file has a .cbr extension, here are some more details of the file: https://imgur.com/1Vl5f1W
Is there anything i can do prior to the next release to get it working?

Thanks for your assistance :]

**Comment by twiddli** [comment]
The scanner shouldn't halt on error anymore in `v0.8.0`
