### ISSUE TITLE
Tags dont load when opening galleries from library

### ISSUE THREAD

**Issue by renox92** [happypandax/happypandax#97]
**Describe the bug**
Tag section doesn't load up when opening gallery from library.

**To Reproduce**
1. Go to 'Library'
2. Click on any gallery
3. See tag section having 0 tags

**Expected behavior**
Tag section displays all tags applied to this gallery.

**Screenshots**
![Screen Shot 2019-03-13 at 11 48 36](https://user-images.githubusercontent.com/35609537/54268738-f5051600-458c-11e9-936a-c82eafe83d1a.png)
![Screen Shot 2019-03-13 at 11 49 34](https://user-images.githubusercontent.com/35609537/54268737-f5051600-458c-11e9-8020-f49d0820cf69.png)

**Environment:**
 - OS: macOS 10.14.3
 - Browsers tested: Chrome 73, Firefox Nightly 69, Safari 12, Opera 57
 - HPX Version 0.8.1

**Additional context**
What doesn't fix the problem:
- refreshing page

What fixes the problem temporarily:
- hitting "update" button next to heart icon (tags won't load again after page refresh)

What fixes the problem:
- clicking address bar and hitting "enter" (Firefox only) 
- copying gallery's url, going to another page, then pasting copied url (alternatively, just opening this url in a new tab)
- using "open link in a new tab" instead of left-clicking gallery from library
After making tags load using these methods tags will load again after refreshing the page.

What makes tags dissappear:
- clicking on "Edit" button (if action from "fixes the problem" was performed, tags will load after refreshing the page, if not - they won't)

**Comment by twiddli** [comment]
fixed in `v0.9.0`
