### ISSUE TITLE
Accessing with Reverse Proxy

### ISSUE THREAD

**Issue by matlai17** [happypandax/happypandax#99]
**Describe the bug**
Web client does not connect to the server when accessed from a reverse proxy. It works when connecting from a local machine (e.g. 192.168.0.101:7008) but not remotely through a reverse proxy. The webpage only has a spinning indicator. The server is a headless Linux machine.

**To Reproduce**
1. Setup HPX
2. Setup nginx to proxy_pass localhost:7008
3. Attempt to access the web page using the url (e.g. happypandax.example.com)

**Expected behavior**
Expected similar functionality as accessing from local network. Instead, the webpage has a spinning circle.

**Logs**
The logs do not mention any errors or events relating to connection issues. However the standard output outputs the following when attempts are made to access the webpage:

Traceback (most recent call last):
  File "site-packages/gevent/pywsgi.py", line 976, in handle_one_response
  File "site-packages/geventwebsocket/handler.py", line 88, in run_application
  File "site-packages/gevent/pywsgi.py", line 924, in run_application
  File "site-packages/gevent/pywsgi.py", line 910, in process_result
  File "site-packages/gevent/pywsgi.py", line 756, in write
AssertionError: The application did not call start_response()
2019-03-24T02:26:04Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '45124', 'HTTP_HOST': 'localhost:7008', (hidden keys: 27)} failed with AssertionError

A new traceback is generated every few seconds as the web client attempts to access the server.

**Environment:**
 - OS: HPX Server/Web Server: Fedora 29; Client: Windows 10
 - Browser and browser version Chrome 72
 - HPX Version 0.81

**Additional context**
The server is in a remote location, so I need to VPN into the server's network to access it locally. As mentioned, when accessed through the local IP, I can access the HPX server normally. I have tried different nginx configurations, with different proxy_header settings, with ssl enabled/disabled, etc, and none of these changes helped.

*Edited above: Linux -> Fedora 29*
Not sure why I didn't supply the exact distro. Must have been half asleep at the time

**Comment by twiddli** [comment]
Hi, I have trouble reproducing this issue.
Can you post one of the tried nginx confs (make sure to remove sensitive parts out)?

**Comment by matlai17** [comment]
Below is one of them. I've altered the proxy_pass to varying addresses including 127.0.0.1 and 0.0.0.0 to no effect. I've also used the configurations with and without those varying proxy_set_header settings that are currently commented out. I've also tried several different combinations of enabled/disabled SSL between NGINX and HPX, all using certs generated by certbot. 

Do I need to change any settings in particular within the config.yaml file to account for nginx?


```
server {
    listen 80;
    listen [::]:80;
    server_name happypandax.example.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443;
    listen [::]:443;
    server_name happypandax.example.com;
    root /var/www/happypandax;

  location / {
    proxy_pass https://localhost:7008;
    gzip off;

    proxy_read_timeout      300;
    proxy_connect_timeout   300;
#    proxy_redirect          off;

#    proxy_set_header    Host                $http_host;
#    proxy_set_header    X-Real-IP           $remote_addr;
#    proxy_set_header    X-Forwarded-Ssl     on;
#    proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
#    proxy_set_header    X-Forwarded-Proto   $scheme;
#    proxy_set_header    X-Frame-Options     SAMEORIGIN;

  }


    ssl_certificate /etc/letsencrypt/live/happypandax.example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/happypandax.example.com/privkey.pem; # managed by Certbot
}
```

**Comment by twiddli** [comment]
Hi, I forgot to answer this. Sorry for that.
First, make sure to have your nginx version be atleast `1.4`. Earlier versions do not have proxy support for WebSocket. Second, an endpoint for the websocket communication was missing. This is handled on `/socket.io`.
Here is a working config:
```
server {
    listen 80;
    listen [::]:80;
    server_name example.me www.example.me;
    charset	utf-8;

    # for websocket
    location /socket.io {
    	proxy_pass http://localhost:7008/socket.io;
        proxy_redirect off;
        proxy_buffering off;

	proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

	proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    location / {
        proxy_pass http://localhost:7008;
	proxy_redirect off;
        gzip off;

        proxy_read_timeout	300;
	proxy_connect_timeout   300;

	proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

	proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

}
```

This could be good to add in the docs.

**Comment by matlai17** [comment]
Thank you very much. It works a treat now. Might be a good thing to add to the documentation.

**Comment by twiddli** [comment]
just wanted to give a heads up, the websocket path was changed from `/socket.io` to `/websocket` in `v0.11.0`
